import '../scripts/test-isolation.mjs';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
// Modulo Playwright opzionale: percorso assoluto come primo argomento, oppure installazione locale.
const {chromium}=await import(process.argv[2]?pathToFileURL(resolve(process.argv[2])).href:'playwright');
const dir=mkdtempSync(join(tmpdir(),'myclean-browser-'));
const {connectStore,migrate}=await import('../server/storage.mjs');
const {provision}=await import('../server/auth.mjs');
const testStore=await connectStore({path:join(dir,'pg')});await migrate(testStore);await provision(testStore,{slug:'test-azienda',name:'Impresa test',email:'admin@example.com',password:'Password-browser-2026!'});await provision(testStore,{slug:'altra-azienda',name:'Altra impresa',email:'admin@example.com',password:'Password-browser-2026!'});await testStore.close();
const child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,PORT:'3138',PGLITE_PATH:join(dir,'pg'),BOOTSTRAP_DEMO:'0',MAIL_MODE:'preview',PUBLIC_APP_URL:'http://localhost:3138'},stdio:['ignore','pipe','pipe']});
let browser;
try{
await once(child.stdout,'data');browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100},locale:'it-IT'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3138');await page.getByLabel('Codice azienda').fill('test-azienda');await page.getByLabel('Email',{exact:true}).fill('admin@example.com');await page.getByLabel('Password',{exact:true}).fill('Password-browser-2026!');await page.getByRole('button',{name:'Accedi',exact:true}).click();await page.getByText('Ore residue pagate',{exact:true}).waitFor();
mkdirSync('test-results',{recursive:true});await page.screenshot({path:'test-results/desktop.png',fullPage:true});
const nav=label=>page.locator('nav').getByRole('button',{name:new RegExp(label)});
await nav('Pacchetti ore').click();await page.getByRole('button',{name:'Configura catalogo',exact:true}).click();await page.getByRole('heading',{name:'Il tuo catalogo parte da qui'}).waitFor();await page.getByRole('button',{name:'Nuovo modello'}).click();await page.getByLabel('Nome del modello').fill('Assistenza flessibile');await page.getByLabel('Ore intere').fill('12');await page.getByLabel('Minuti aggiuntivi').fill('30');await page.getByLabel('Descrizione').fill('Servizi concordati con il cliente');await page.getByRole('button',{name:'Salva',exact:true}).click();await page.getByRole('heading',{name:'Assistenza flessibile',exact:true}).waitFor();
await nav('Clienti').click();await page.getByRole('button',{name:'Nuovo cliente'}).click();await page.getByLabel('Nome cliente').fill('Cliente prova browser');await page.getByLabel('Email',{exact:true}).fill('prova@example.com');await page.getByLabel('Telefono').fill('000 000000');await page.getByLabel('Indirizzo').fill('Via Fittizia 99');await page.getByRole('button',{name:'Salva',exact:true}).click();await page.getByRole('heading',{name:'Cliente prova browser',exact:true}).waitFor();
await page.getByLabel('Cerca cliente').fill('Cliente prova browser');await page.getByRole('button',{name:'Apri scheda'}).click();await page.getByRole('button',{name:'Modifica cliente'}).click();await page.getByLabel('Telefono').fill('000 111111');await page.getByRole('button',{name:'Salva',exact:true}).click();await page.locator('.contact-panel').filter({hasText:'000 111111'}).waitFor();
await page.getByRole('button',{name:'＋ Pacchetto',exact:true}).click();await page.getByLabel('Saldo iniziale').fill('60');await page.getByLabel('Confermo che il pagamento').check();await page.getByRole('button',{name:'Salva',exact:true}).click();await page.locator('.package').waitFor();
await page.getByRole('button',{name:'Stampa riepilogo'}).waitFor();await page.emulateMedia({media:'print'});await page.pdf({path:'test-results/riepilogo.pdf',format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});
await nav('Interventi').click();await page.getByRole('button',{name:'Nuovo intervento'}).click();await page.getByLabel('Cliente *').selectOption({label:'Cliente prova browser'});const select=page.getByLabel('Pacchetto pagato');const options=await select.locator('option').allTextContents();await select.selectOption({label:options[1]});await page.getByLabel('Data e ora').fill(new Date(Date.now()-86400000).toISOString().slice(0,16));await page.getByLabel('Servizio').fill('Pulizia test browser');await page.getByLabel('Operatore o squadra').fill('Squadra demo');await page.getByLabel('Durata in minuti').fill('120');await page.getByRole('button',{name:'Salva',exact:true}).click();await page.getByRole('alert').filter({hasText:'Ore libere insufficienti'}).waitFor();await page.getByLabel('Durata in minuti').fill('20');await page.getByLabel('Numero operatori').fill('2');await page.getByRole('button',{name:'Salva',exact:true}).click();
const row=page.locator('tr').filter({hasText:'Pulizia test browser'});await row.getByRole('button',{name:'Completa',exact:true}).click();await page.getByLabel('Durata in minuti').fill('20');await page.getByRole('button',{name:'Salva',exact:true}).click();await row.getByRole('button',{name:'Approva',exact:true}).click();assert((await page.locator('.approval').innerText()).includes('0,67 h'));await page.getByRole('button',{name:'Conferma operazione'}).click();await row.getByRole('button',{name:'Rettifica'}).click();await page.getByLabel('Durata in minuti').fill('15');await page.getByLabel('Motivazione obbligatoria').fill('Verifica durata effettiva');await page.getByRole('button',{name:'Conferma operazione'}).click();await row.getByRole('button',{name:'Annulla',exact:true}).click();await page.getByLabel('Motivazione obbligatoria').fill('Annullamento test browser');await page.getByRole('button',{name:'Conferma operazione'}).click();await row.getByText('Annullato',{exact:true}).waitFor();
await nav('Pacchetti ore').click();await page.getByRole('button',{name:'Pacchetti assegnati',exact:true}).click();const card=page.locator('.package').filter({hasText:'Cliente prova browser'});assert((await card.locator('.balance').innerText()).includes('1 h'));await card.getByRole('button',{name:'Rinnova'}).click();await page.getByRole('button',{name:'Salva',exact:true}).click();await page.waitForFunction(()=>Array.from(document.querySelectorAll('.package')).filter(el=>el.textContent.includes('Cliente prova browser')).length===2);
await page.getByRole('button',{name:'Configura catalogo',exact:true}).click();await page.getByRole('button',{name:'Modifica modello',exact:true}).click();await page.getByLabel('Nome del modello').fill('Nuova offerta');await page.getByLabel('Ore intere').fill('8');await page.getByLabel('Regola di conteggio').selectOption('team');await page.getByLabel('Motivazione della modifica').fill('Aggiornamento offerta');await page.getByRole('button',{name:'Salva',exact:true}).click();await page.getByRole('heading',{name:'Nuova offerta',exact:true}).waitFor();await page.getByRole('button',{name:'Disattiva',exact:true}).click();await page.getByLabel('Motivazione obbligatoria').fill('Fine promozione');await page.getByRole('button',{name:'Conferma operazione'}).click();await page.getByRole('heading',{name:'Nessun modello attivo'}).waitFor();await page.getByLabel('Mostra anche i modelli disattivati').check();await page.getByRole('button',{name:'Riattiva',exact:true}).click();await page.getByLabel('Motivazione obbligatoria').fill('Nuova disponibilità');await page.getByRole('button',{name:'Conferma operazione'}).click();await page.getByText('Disponibile',{exact:true}).waitFor();await page.screenshot({path:'test-results/catalogo-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/catalogo-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.setViewportSize({width:1440,height:1100});await page.getByRole('button',{name:'Pacchetti assegnati',exact:true}).click();assert.equal(await page.locator('.package .tier').filter({hasText:'Assistenza flessibile'}).count(),2);
await nav('Storico attività').click();await page.getByText('Verifica durata effettiva',{exact:true}).waitFor();const download=page.waitForEvent('download');await page.getByRole('link',{name:'Esporta CSV'}).click();assert.equal((await download).suggestedFilename(),'myclean-esportazione.csv');
await nav('Panoramica').click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.getByRole('button',{name:'Nuovo intervento'}).click();await page.screenshot({path:'test-results/mobile-form.png',fullPage:true});await page.getByRole('button',{name:'Chiudi',exact:true}).click();assert.deepEqual(errors,[]);console.log('Browser OK: creazione/modifica cliente, pacchetto importato, disponibilità, completamento, approvazione, rettifica, annullamento, rinnovo, CSV, stampa, mobile.');
}finally{if(browser)await browser.close();const done=once(child,'exit');child.kill();await done;rmSync(dir,{recursive:true,force:true})}
