import '../scripts/test-isolation.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openDB,mutate,snapshot,seed} from '../server/db.mjs';
const past=new Date(Date.now()-86400000).toISOString();const future=new Date(Date.now()+86400000).toISOString();
function fixture(rule='operator',paid=true,initial=1200){const db=openDB(':memory:');let seq=0;const run=(a,i,k)=>mutate(db,a,i,k||`test-${++seq}`);const client=run('client',{name:'Test',email:'',phone:'',address:''}).value;const p=run('package',{clientId:client.id,tier:'Star',initial,rule,paid}).value;const add=(overrides={})=>run('intervention',{packageId:p.id,date:past,service:'Pulizia',team:'Test',duration:120,operators:2,status:'pending',...overrides}).value;const balance=()=>snapshot(db).packages[0];return{db,run,add,balance,p}}
test('minuti interi, taglio originario e regola operatore/squadra',()=>{for(const [rule,cost] of [['operator',240],['team',120]]){const f=fixture(rule,true,600);const i=f.add();assert.equal(f.balance().original,1200);assert.equal(f.balance().initial,600);assert.equal(f.balance().committed,cost);assert.equal(f.balance().remaining,600);assert.equal(f.balance().free,600-cost);assert.throws(()=>f.add({duration:1.5}),/intero/);assert.throws(()=>f.add({operators:0}),/intero/);f.run('approve',{id:i.id});assert.equal(f.balance().consumed,cost);assert.equal(f.balance().committed,0);f.db.close()}});
test('blocca disponibilità insufficiente e pacchetti non pagati senza scritture parziali',()=>{const f=fixture('operator',true,300);f.add();const before=snapshot(f.db);assert.throws(()=>f.add({duration:31}),/insufficienti/);assert.deepEqual(snapshot(f.db),before);f.db.close();const u=fixture('team',false);assert.throws(()=>u.add(),/pagamento/);u.run('pay',{id:u.p.id});u.add();assert.throws(()=>u.run('pay',{id:u.p.id}),/già confermato/);u.db.close()});
test('approvazione idempotente e doppio addebito impedito',()=>{const f=fixture();const i=f.add();const before=snapshot(f.db).audit.length;const one=f.run('approve',{id:i.id},'same');const two=f.run('approve',{id:i.id},'same');assert.deepEqual(one,two);assert.equal(f.balance().consumed,240);assert.equal(snapshot(f.db).audit.length,before+1);assert.throws(()=>f.run('approve',{id:i.id}),/Solo/);assert.throws(()=>f.run('cancel',{id:i.id,reason:'x'},'same'),/Identificativo/);f.db.close()});
test('rettifica preserva gli impegni altrui, richiede motivo e registra prima/dopo',()=>{const f=fixture('operator',true,600);const i=f.add();f.run('approve',{id:i.id});f.add({duration:150,status:'planned'});assert.throws(()=>f.run('rectify',{id:i.id,duration:151,operators:2,reason:'Correzione'}),/insufficienti/);assert.throws(()=>f.run('rectify',{id:i.id,duration:100,operators:2,reason:'  '}),/obbligatori/);f.run('rectify',{id:i.id,duration:90,operators:2,reason:'Durata verificata'});assert.equal(f.balance().consumed,180);assert.equal(f.balance().free,120);const log=snapshot(f.db).audit[0];assert.equal(JSON.parse(log.beforeValue).duration,120);assert.equal(JSON.parse(log.afterValue).duration,90);assert.equal(log.reason,'Durata verificata');f.db.close()});
test('annullamenti restituiscono consumi o liberano impegni una sola volta',()=>{for(const status of ['planned','pending','approved']){const f=fixture();const i=f.add({status:status==='approved'?'pending':status});if(status==='approved')f.run('approve',{id:i.id});f.run('cancel',{id:i.id,reason:'Annullamento cliente'},'cancel');f.run('cancel',{id:i.id,reason:'Annullamento cliente'},'cancel');assert.equal(f.balance().remaining,1200);assert.equal(f.balance().free,1200);assert.equal(f.balance().committed,0);assert.equal(snapshot(f.db).interventions.length,1);assert.throws(()=>f.run('cancel',{id:i.id,reason:'Ripeti'}),/già annullato/);f.db.close()}});
test('completamento usa durata effettiva, rispetta disponibilità e vieta il futuro',()=>{const f=fixture('operator',true,300);assert.throws(()=>f.add({date:future}),/futuro/);const i=f.add({status:'planned',date:future});assert.throws(()=>f.run('complete',{id:i.id,duration:100,operators:2}),/futuro/);assert.throws(()=>f.run('approve',{id:i.id}),/futuro/);f.run('cancel',{id:i.id,reason:'Test'});const j=f.add({status:'planned'});assert.throws(()=>f.run('complete',{id:j.id,duration:151,operators:2}),/insufficienti/);f.run('complete',{id:j.id,duration:100,operators:2});assert.equal(f.balance().committed,200);assert.equal(f.balance().consumed,0);assert.equal(snapshot(f.db).interventions.find(x=>x.id===j.id).status,'pending');f.run('approve',{id:j.id});assert.equal(f.balance().remaining,100);f.db.close()});
test('rinnovo conserva il pacchetto precedente e isola il saldo',()=>{const f=fixture();f.add();const old=f.balance();f.run('package',{clientId:f.p.clientId,tier:'Love',initial:2400,rule:'team',paid:true,renewedFrom:f.p.id});assert.equal(snapshot(f.db).packages.length,2);assert.deepEqual(snapshot(f.db).packages.find(p=>p.id===old.id),old);f.db.close()});
test('dati e chiavi idempotenti persistono alla riapertura; seed eseguito una sola volta',()=>{const dir=mkdtempSync(join(tmpdir(),'myclean-test-'));try{const path=join(dir,'test.sqlite');let db=openDB(path);seed(db);const before=snapshot(db);mutate(db,'client',{name:'Persistenza'},'persist');const after=snapshot(db);db.close();db=openDB(path);seed(db);assert.deepEqual(snapshot(db),after);assert.equal(after.clients.length,before.clients.length+1);mutate(db,'client',{name:'Persistenza'},'persist');assert.deepEqual(snapshot(db),after);db.close()}finally{rmSync(dir,{recursive:true,force:true})}});
