import {useEffect,useState,ReactNode} from 'react';
import {Platform} from './platform';
import {mfaQrDataUrl} from './mfa-qr';
import {ActiveSessions} from './session-security';

export type Session={user:{id:string;tenantId:string;homeTenantId?:string;name:string;email:string;role:'manager'|'operator'|'platform_admin';mfaEnabled?:boolean};csrf:string};
export async function post(path:string,input:unknown,csrf?:string,tenantId?:string) {
  const res=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{}),...(tenantId?{'X-Tenant-Context':tenantId}:{}),'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(input)});
  const result=await res.json();
  if(!res.ok)throw Error(result.error||'Operazione non riuscita.');
  return result;
}

export function Access({children}:{children:(session:Session,logout:()=>void,home:()=>void)=>ReactNode}) {
  const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[resetBusy,setResetBusy]=useState(false),[resetMessage,setResetMessage]=useState(''),[mfaChallenge,setMfaChallenge]=useState('');
  const [token,setToken]=useState(()=>new URLSearchParams(location.hash.slice(1)).get('reset'));
  useEffect(()=>{document.title='luviqAI · Gestionale servizi';fetch('/api/me').then(async r=>{if(r.ok)setSession(await r.json());else if(r.status!==401)throw Error('Server non disponibile.');}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  async function logout(){try{if(session)await post('logout',{},session.csrf);}catch{}setSession(null);}
  async function submit(e:React.FormEvent<HTMLFormElement>) {
    e.preventDefault();setBusy(true);setError('');
    const form=Object.fromEntries(new FormData(e.currentTarget));
    try {
      if(token){await post('reset-password',{token,password:form.password});setToken(null);history.replaceState(null,'',location.pathname);setMessage('Password aggiornata. Accedi con la nuova password.');}
      else {const result=await post('login',form);if(result.mfaRequired){setMfaChallenge(result.challenge);setMessage('Password corretta. Inserisci ora il codice dell’app autenticatore.');}else setSession(result);}
    }catch(e:any){setError(e.message);}finally{setBusy(false);}
  }
  async function requestReset(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();setResetBusy(true);setError('');setResetMessage('');
    try{
      const form=Object.fromEntries(new FormData(e.currentTarget));
      const result=await post('request-password-reset',form);
      setResetMessage(result.message||'Se i dati corrispondono a un account attivo, riceverai un link via email.');
      e.currentTarget.reset();
    }catch(e:any){setError(e.message)}finally{setResetBusy(false)}
  }
  async function submitMfa(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();setBusy(true);setError('');
    try{setSession(await post('mfa/login',{challenge:mfaChallenge,...Object.fromEntries(new FormData(e.currentTarget))}));setMfaChallenge('');setMessage('');}
    catch(e:any){setError(e.message)}finally{setBusy(false)}
  }
  if(loading)return <div className="auth-shell"><p>Verifica accesso…</p></div>;
  async function home(){if(!session)return;try{setSession(await post('platform/switch',{},session.csrf));}catch{location.reload();}}
  if(session&&!token){
    if(session.user.role==='platform_admin'&&session.user.tenantId===session.user.homeTenantId)return <Platform session={session} onSession={setSession} onLogout={logout}/>;
    return <>{children(session,logout,home)}</>;
  }
  return <div className="auth-shell"><div className="auth-story"><span className="brand-icon">✳</span><div className="eyebrow">UN PRODOTTO LUVIQAI</div><h1>La tua impresa.<br/>Ogni ora, al suo posto.</h1><p>Clienti, squadre e pacchetti ore in uno spazio riservato alla tua azienda.</p><div className="auth-points">◈ Dati separati per impresa<br/>◷ Saldi e attività verificabili<br/>✓ Accessi personali</div></div><section className="auth-card"><div className="eyebrow">GESTIONALE SERVIZI</div><h2>{token?'Scegli la nuova password':mfaChallenge?'Verifica in due passaggi':'Accedi al tuo spazio'}</h2><p>{token?'Il link di recupero è monouso.':mfaChallenge?'Apri la tua app autenticatore e inserisci il codice a 6 cifre. Puoi usare anche un codice di recupero.':'Usa il codice della tua impresa e il tuo account personale.'}</p>{mfaChallenge?<form onSubmit={submitMfa}><label>Codice MFA o recupero<input name="code" autoComplete="one-time-code" inputMode="text" autoCapitalize="characters" spellCheck={false} required maxLength={20} autoFocus placeholder="123456 oppure XXXXX-XXXXX"/></label>{error&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert success">{message}</div>}<button disabled={busy}>{busy?'Verifica…':'Verifica e accedi'}</button><button type="button" className="text" onClick={()=>{setMfaChallenge('');setMessage('');setError('')}}>← Torna al login</button></form>:<><form onSubmit={submit}>
    {!token&&<><label>Codice azienda<input name="slug" autoComplete="organization" required placeholder="es. my-clean"/></label><label>Email<input name="email" autoComplete="username" type="email" required/></label></>}
    <label>{token?'Nuova password':'Password'}<input name="password" type="password" autoComplete={token?'new-password':'current-password'} required minLength={token?12:undefined} maxLength={200}/></label>
    {error&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert success">{message}</div>}
    <button disabled={busy}>{busy?'Attendi…':token?'Aggiorna password':'Accedi'}</button>
  </form>{!token&&<details><summary>Hai dimenticato la password?</summary><form onSubmit={requestReset}><p>Inserisci il codice azienda e l’email del tuo account. Se i dati corrispondono a un account attivo, riceverai un link monouso valido 30 minuti.</p><label>Codice azienda<input name="slug" autoComplete="organization" required placeholder="es. my-clean"/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label>{resetMessage&&<div className="alert success" role="status">{resetMessage}</div>}<button disabled={resetBusy}>{resetBusy?'Invio…':'Invia link di recupero'}</button></form></details>}</>}<small>Realizzata da luviqAI · Versione riservata<br/><a href="/privacy.html">Privacy Policy</a> · <a href="/cookie.html">Cookie Policy</a> · <a href="/terms.html">Termini di utilizzo</a></small></section></div>;
}

export function Account({session,company,team,onSaved,onLogout}:{session:Session;company:any;team:any[];onSaved:()=>Promise<void>;onLogout:()=>void}) {
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[logo,setLogo]=useState(company.logoData||''),[mfa,setMfa]=useState<any>(null),[mfaSetup,setMfaSetup]=useState<any>(null),[recovery,setRecovery]=useState<string[]>([]);
  async function submit(e:React.FormEvent<HTMLFormElement>,action:string){
    e.preventDefault();setBusy(true);setError('');setMessage('');const form=e.currentTarget;
    try{await post(action,{...Object.fromEntries(new FormData(form)),...(action==='company'?{logoData:logo}:{})},session.csrf,session.user.tenantId);if(action==='password'){onLogout();return;}await onSaved();setMessage(action==='user'?'Account creato. Email di riepilogo inserita in coda.':'Modifiche salvate.');if(action==='user')form.reset();}catch(e:any){setError(e.message);}finally{setBusy(false);}
  }
  useEffect(()=>{if(session.user.role==='manager')fetch('/api/mfa/status',{headers:{'X-Tenant-Context':session.user.tenantId}}).then(r=>r.ok?r.json():null).then(setMfa).catch(()=>{});},[session.user.id,session.user.tenantId]);
  async function startMfa(){setBusy(true);setError('');setMessage('');try{setMfaSetup(await post('mfa/setup',{},session.csrf,session.user.tenantId));setRecovery([]);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function enableMfaForm(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const result=await post('mfa/enable',Object.fromEntries(new FormData(e.currentTarget)),session.csrf,session.user.tenantId);setRecovery(result.recoveryCodes||[]);setMfa({...mfa,enabled:true});setMfaSetup(null);setMessage('Verifica in due passaggi attivata. Conserva i codici di recupero in un posto sicuro.');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function disableMfaForm(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await post('mfa/disable',Object.fromEntries(new FormData(e.currentTarget)),session.csrf,session.user.tenantId);setMfa({...mfa,enabled:false});setRecovery([]);setMessage('Verifica in due passaggi disattivata.');(e.currentTarget as HTMLFormElement).reset();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function chooseLogo(file?:File){if(!file)return;setError('');if(!['image/png','image/jpeg'].includes(file.type)||file.size>500*1024){setError('Scegli un logo PNG o JPEG di massimo 500 KB.');return;}try{const reader=new FileReader();const value=await new Promise<string>((resolve,reject)=>{reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('Impossibile leggere il logo.'));reader.readAsDataURL(file)});setLogo(value);}catch(e:any){setError(e.message)}}
  async function toggle(user:any){if(!confirm(`${user.active?'Disattivare':'Riattivare'} l’account di ${user.name}? Le sessioni precedenti saranno chiuse.`))return;setBusy(true);setError('');setMessage('');try{await post('user',{id:user.id,active:!user.active},session.csrf,session.user.tenantId);await onSaved();setMessage(`Account ${user.active?'disattivato':'riattivato'}.`);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function updateUser(e:React.FormEvent<HTMLFormElement>,user:any){e.preventDefault();setBusy(true);setError('');setMessage('');try{const data=Object.fromEntries(new FormData(e.currentTarget));await post('user',{id:user.id,mode:'update',...data},session.csrf,session.user.tenantId);await onSaved();setMessage(`Account di ${user.name} aggiornato. Le sessioni precedenti sono state chiuse.`);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function resetUserPassword(e:React.FormEvent<HTMLFormElement>,user:any){e.preventDefault();setBusy(true);setError('');setMessage('');const form=e.currentTarget;try{const data=Object.fromEntries(new FormData(form));await post('user',{id:user.id,mode:'reset-password',password:data.password},session.csrf,session.user.tenantId);form.reset();setMessage(`Password di ${user.name} reimpostata. Le sessioni precedenti sono state chiuse.`);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <div className="settings">{error&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert success">{message}</div>}
    {session.user.role!=='operator'&&<><section className="settings-card"><h2>Identità dell’impresa</h2><p>Codice di accesso: <b>{company.slug}</b>. Le modifiche riguardano soltanto questa azienda.</p><form onSubmit={e=>submit(e,'company')}><div className="logo-upload"><div className="logo-preview">{logo?<img src={logo} alt="Anteprima logo aziendale"/>:<span>Nessun logo caricato</span>}</div><label>Logo aziendale (PNG o JPEG)<input type="file" accept="image/png,image/jpeg" disabled={busy} onChange={e=>void chooseLogo(e.target.files?.[0])}/></label><p className="help">Massimo 500 KB. Preferisci un PNG trasparente. Il logo compare nei preventivi salvati dopo questa modifica.</p>{logo&&<button type="button" className="text danger" disabled={busy} onClick={()=>setLogo('')}>Rimuovi logo</button>}</div><label>Nome impresa<input name="name" defaultValue={company.name} required maxLength={300}/></label><div className="form-grid"><label>Sigla o simbolo del logo<input name="logoText" defaultValue={company.logoText} required maxLength={10}/></label><label>Colore aziendale<input name="brandColor" type="color" defaultValue={company.brandColor}/></label></div><label>Indirizzo<input name="address" defaultValue={company.address}/></label><label>Email aziendale<input name="email" type="email" defaultValue={company.email}/></label><p className="help">Questo indirizzo riceve il riepilogo delle risposte ai preventivi ed è usato come recapito per rispondere alle email. In simulazione i messaggi restano in Email e notifiche.</p><div className="form-grid"><label>Telefono aziendale<input name="phone" defaultValue={company.phone||''} maxLength={80}/></label><label>Sito web<input name="website" defaultValue={company.website||''} maxLength={200}/></label></div><label>Partita IVA / Codice fiscale<input name="taxId" defaultValue={company.taxId||''} maxLength={100}/></label><button disabled={busy}>Salva identità</button></form></section>
    <section className="settings-card"><h2>Account della tua azienda</h2><p>I responsabili gestiscono tutti i dati aziendali. Gli operatori vedono e completano soltanto gli interventi assegnati.</p>{team.map(user=><div className="member" key={user.id}><div><b>{user.name}</b><p>{user.email} · {user.role==='manager'?'Responsabile':'Operatore'} · {user.active?'Attivo':'Disattivato'}</p>{user.id!==session.user.id&&<div className="account-tools"><details><summary>Modifica account</summary><form onSubmit={e=>updateUser(e,user)}><label>Nome<input name="name" defaultValue={user.name} required maxLength={300}/></label><label>Email<input name="email" type="email" defaultValue={user.email} required/></label><label>Ruolo<select name="role" defaultValue={user.role}><option value="operator">Operatore</option><option value="manager">Responsabile</option></select></label><button disabled={busy}>Salva modifiche</button></form></details><details><summary>Reimposta password</summary><form onSubmit={e=>resetUserPassword(e,user)}><label>Nuova password<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={200}/></label><p className="help">Dopo il salvataggio tutte le sessioni dell’utente verranno chiuse.</p><button disabled={busy}>Reimposta password</button></form></details></div>}</div>{user.id!==session.user.id&&<button className="secondary" disabled={busy} onClick={()=>toggle(user)}>{user.active?'Disattiva':'Riattiva'}</button>}</div>)}<details><summary>Crea un account</summary><form onSubmit={e=>submit(e,'user')}><label>Nome<input name="name" required maxLength={300}/></label><label>Email<input name="email" type="email" required/></label><label>Ruolo<select name="role"><option value="operator">Operatore</option><option value="manager">Responsabile</option></select></label><label>Password iniziale (almeno 12 caratteri)<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={200}/></label><p>La mail di riepilogo viene inviata automaticamente senza includere la password. Comunica la password iniziale separatamente.</p><button disabled={busy}>Crea account</button></form></details></section></>}
    {session.user.role==='manager'&&<section className="settings-card"><h2>Verifica in due passaggi</h2><p>Protegge l’account con un secondo codice oltre alla password.</p>{mfa?.available===false?<div className="alert">La MFA deve essere abilitata nella configurazione del server prima di poterla attivare.</div>:mfa?.enabled?<><div className="alert success">MFA attiva su questo account.</div><form onSubmit={disableMfaForm}><label>Password attuale<input name="password" type="password" autoComplete="current-password" required/></label><label>Codice autenticatore<input name="code" inputMode="numeric" autoComplete="one-time-code" required maxLength={6}/></label><button className="secondary" disabled={busy}>Disattiva MFA</button></form></>:mfaSetup?<><p>Apri Google Authenticator (o un’altra app TOTP), premi <b>＋</b> e scegli <b>Scansiona un codice QR</b>.</p><div style={{display:'flex',justifyContent:'center',padding:'18px 0'}}><img src={mfaQrDataUrl(mfaSetup.uri)} alt="QR code per configurare la verifica in due passaggi" width="238" height="238" style={{maxWidth:'100%',height:'auto',background:'#fff',padding:10,borderRadius:12}}/></div><details><summary>Non riesci a scansionare il QR?</summary><p>Configura manualmente l’account con questa chiave e seleziona <b>Basata sul tempo</b>.</p><label>Chiave segreta<input readOnly value={mfaSetup.secret}/></label></details><form onSubmit={enableMfaForm}><label>Codice a 6 cifre<input name="code" inputMode="numeric" autoComplete="one-time-code" required minLength={6} maxLength={6}/></label><button disabled={busy}>Conferma e attiva MFA</button></form></>:<button disabled={busy||!mfa} onClick={startMfa}>Configura MFA</button>}{recovery.length>0&&<div className="alert"><b>Codici di recupero — mostrati una sola volta</b><pre>{recovery.join('\n')}</pre></div>}</section>}
    <ActiveSessions session={session}/>
    <section className="settings-card"><h2>La tua password</h2><p>{session.user.name} · {session.user.email}. La modifica chiude tutte le tue sessioni.</p><form onSubmit={e=>submit(e,'password')}><label>Password attuale<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>Nuova password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={200} required/></label><button disabled={busy}>Cambia password</button></form></section>
  </div>;
}
