import React,{useEffect,useState} from 'react';
import {Session} from './access';
const money=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n/100);
type Reply={text:string;rows?:string[];proposal?:any;quoteId?:number;question?:string;saved?:boolean};
export function Assistant({session,onSaved}:{session:Session;onSaved:()=>Promise<void>}){
 const[status,setStatus]=useState<any>(null),[message,setMessage]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[replies,setReplies]=useState<Reply[]>([]);
 async function request(path:string,input?:any){const r=await fetch('/api/ai/'+path,{method:input?'POST':'GET',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf,'X-Tenant-Context':session.user.tenantId},...(input?{body:JSON.stringify(input)}:{})});const body=await r.json();if(!r.ok)throw Error(body.error||'Assistente non disponibile.');return body;}
 async function load(){try{setStatus(await request('status'));setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{void load()},[]);
 async function ask(quick?:string){if(busy)return;setBusy(true);setError('');try{const result=await request('chat',quick?{quick}:{message,consent});setReplies(v=>[...v.slice(-19),{...result,question:quick?({low_balance:'Pacchetti con saldo basso',overdue_invoices:'Fatture scadute',pending_jobs:'Interventi da approvare'} as any)[quick]:message}]);setMessage('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function confirm(token:string){if(busy)return;setBusy(true);setError('');try{const result=await request('confirm',{token,confirm:true});setReplies(v=>v.map(r=>r.proposal?.token===token?{...r,saved:true,text:result.text}:r));await onSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="ai-center">
 <div className="hero"><div><span className="eyebrow">UN AIUTO NEL LAVORO QUOTIDIANO</span><h2>Il tuo assistente luviqAI</h2><p>Consulta ore e scadenze. Prepara un preventivo e controllalo prima di salvarlo.</p></div><div className="hero-mark" aria-hidden="true">✳</div></div>
 <div className="alert"><b>{status?.enabled?'OpenRouter gratuito configurato':'Testo libero da configurare'}</b><p>{status?.enabled?`Modello: ${status.model}. Disponibilità soggetta ai limiti del servizio gratuito.`:status?.reason||'Verifica configurazione…'}</p><button className="secondary" disabled={busy} onClick={()=>void load()}>Verifica configurazione</button></div>
 <div className="actions ai-quick">{[['low_balance','Pacchetti ≤ 5 ore'],['overdue_invoices','Fatture scadute'],['pending_jobs','Interventi da approvare']].map(([key,label])=><button className="secondary" key={key} disabled={busy} onClick={()=>void ask(key)}>{label}</button>)}</div><p className="muted">Le consultazioni rapide funzionano senza AI e non inviano dati esterni.</p>
 <div className="ai-conversation" aria-live="polite">{!replies.length?<div className="empty"><h3>Da cosa vuoi iniziare?</h3><p>Scegli una consultazione oppure scrivi una richiesta completa. Per un preventivo indica cliente, servizio, quantità, prezzo netto e IVA.</p></div>:replies.map((r,index)=><article className="ai-reply" key={index}><p className="ai-question">{r.question}</p><p>{r.text}</p>{r.rows&&<ul>{r.rows.map((row,i)=><li key={i}>{row}</li>)}</ul>}{r.proposal&&!r.saved&&<div className="ai-proposal"><span className="badge pending">Da confermare · scade tra 15 minuti</span><h3>{r.proposal.title}</h3><p><b>{r.proposal.client}</b> · Data {r.proposal.issueDate} · Validità {r.proposal.validUntil}</p><div className="table-wrap"><table><thead><tr><th>Servizio</th><th>Quantità</th><th>Prezzo netto</th><th>IVA</th><th>Sconto</th><th>Totale</th></tr></thead><tbody>{r.proposal.lines.map((l:any,i:number)=><tr key={i}><td>{l.description}</td><td>{l.quantity/100}</td><td>{money(l.unitPrice)}</td><td>{l.vat/100}%</td><td>{l.discount/100}%</td><td>{money(l.total)}</td></tr>)}</tbody></table></div><p>Imponibile {money(r.proposal.net)} · IVA {money(r.proposal.tax)} · <b>Totale {money(r.proposal.total)}</b></p><div className="actions"><button disabled={busy} onClick={()=>void confirm(r.proposal.token)}>Conferma e salva bozza</button><button className="secondary" disabled={busy} onClick={()=>setReplies(v=>v.map((item,i)=>i===index?{...item,proposal:undefined,text:'Proposta scartata. Nessun preventivo salvato.'}:item))}>Scarta proposta</button></div></div>}</article>)}</div>
 <form className="ai-compose" onSubmit={e=>{e.preventDefault();void ask()}}><label>La tua richiesta<textarea maxLength={2000} required value={message} onChange={e=>setMessage(e.target.value)} placeholder="Es. Prepara un preventivo per Casa Aurora: 2 ore di pulizia a 25 euro/ora, IVA 22%."/></label><label className="ai-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Invia il testo che scrivo a OpenRouter e al fornitore del modello. Per queste prove userò dati fittizi e non inserirò credenziali o dati riservati.</label><p className="help">Ogni messaggio è indipendente. I risultati del database e la cronologia della chat restano nel gestionale; il testo della richiesta viene inviato al servizio AI. Controlla sempre le proposte.</p><button disabled={busy||!status?.enabled||!consent||!message.trim()}>{busy?'Elaborazione…':'Invia richiesta'}</button>{error&&<div className="alert error" role="alert">{error}</div>}</form>
 </section>;
}
