import React,{useEffect,useRef,useState} from 'react';
import './assistant.css';
import {Session} from './access';
const money=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n/100);
type Reply={text:string;rows?:string[];proposal?:any;quoteId?:number;question?:string;saved?:boolean};
export function Assistant({session,onSaved,context}:{session:Session;onSaved:()=>Promise<void>;context?:{page?:string;clientId?:number|null}}){
 const[open,setOpen]=useState(false),[details,setDetails]=useState(false);
 const launcher=useRef<HTMLButtonElement>(null),composer=useRef<HTMLTextAreaElement>(null),thread=useRef<HTMLDivElement>(null);
 function close(){setOpen(false);requestAnimationFrame(()=>launcher.current?.focus())}
 useEffect(()=>{if(open)composer.current?.focus()},[open]);
 const[status,setStatus]=useState<any>(null),[message,setMessage]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[replies,setReplies]=useState<Reply[]>([]);
 async function request(path:string,input?:any){const r=await fetch('/api/ai/'+path,{method:input?'POST':'GET',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf,'X-Tenant-Context':session.user.tenantId},...(input?{body:JSON.stringify(input)}:{})});const body=await r.json();if(!r.ok)throw Error(body.error||'Assistente non disponibile.');return body;}
 async function load(){try{setStatus(await request('status'));setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(open)void load()},[open]);
 useEffect(()=>{if(open&&thread.current)thread.current.scrollTop=thread.current.scrollHeight},[replies,busy,open]);
 async function ask(quick?:string){if(busy)return;setBusy(true);setError('');try{const result=await request('chat',quick?{quick,context}:{message,consent,context});setReplies(v=>[...v.slice(-19),{...result,question:quick?({context_summary:'Cosa richiede attenzione qui?',today_work:'Lavoro di oggi',low_balance:'Pacchetti con saldo basso',overdue_invoices:'Fatture scadute',pending_jobs:'Interventi da approvare'} as any)[quick]:message}]);setMessage('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function confirm(token:string){if(busy)return;setBusy(true);setError('');try{const result=await request('confirm',{token,confirm:true});setReplies(v=>v.map(r=>r.proposal?.token===token?{...r,saved:true,text:result.text}:r));await onSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="chat-widget">
 {open&&<section id="luviq-chat" className="chat-panel" role="dialog" aria-label="Assistente luviqAI" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close()}}}>
 <div className="chat-header"><span className="chat-symbol" aria-hidden="true">✳</span><div className="chat-identity"><strong>luviqAI</strong><span><i/>{busy?'Sto elaborando…':'Il tuo assistente di lavoro'}</span></div><button className="chat-icon" aria-label="Informazioni sulla chat" aria-expanded={details} onClick={()=>setDetails(v=>!v)}>ⓘ</button><button className="chat-icon" aria-label="Riduci chat" onClick={close}>−</button></div>
 {details&&<div className="chat-details"><b>{status?.enabled?'OpenRouter gratuito attivo':'Testo libero da configurare'}</b><p>{status?.enabled?`Modello: ${status.model}`:status?.reason||'Verifica configurazione…'}</p><p>Ogni richiesta è indipendente: includi tutti i dettagli. La chat resta disponibile durante la navigazione e si azzera uscendo o ricaricando la pagina.</p><button className="secondary" disabled={busy} onClick={()=>void load()}>Verifica configurazione</button></div>}
 <div className="chat-thread" ref={thread} role="log" aria-live="polite" aria-relevant="additions text">
 {!replies.length&&<div className="chat-welcome"><span className="chat-orbit" aria-hidden="true">✳</span><span className="chat-eyebrow">MENO PASSAGGI, PIÙ TEMPO</span><h2>Come posso aiutarti?</h2><p>Un’occhiata alle ore, una scadenza da controllare o un preventivo da preparare.</p><div className="chat-suggestions">{[['context_summary','Cosa richiede attenzione qui?','Riepilogo della pagina corrente'],['today_work','Lavoro di oggi','Vedi gli interventi della giornata'],['overdue_invoices','Fatture scadute','Tieni d’occhio gli incassi'],['pending_jobs','Interventi da approvare','Rivedi il lavoro completato']].map(([key,label,hint])=><button className="secondary" key={key} disabled={busy} onClick={()=>void ask(key)}><span><b>{label}</b><small>{hint}</small></span><span aria-hidden="true">↗</span></button>)}</div><small>Consultazioni rapide · nessun dato inviato all’AI</small></div>}
 {replies.map((r,index)=><div className="chat-exchange" key={index}><div className="chat-user">{r.question}</div><div className="chat-answer"><span className="chat-answer-label">✳ luviqAI</span><p>{r.text}</p>{!!r.rows?.length&&<ul>{r.rows.map((row,i)=><li key={i}>{row}</li>)}</ul>}{r.proposal&&!r.saved&&<div className="chat-proposal"><span className="badge pending">Da confermare</span><h3>{r.proposal.title}</h3><p><b>{r.proposal.client}</b><br/>Data {r.proposal.issueDate}<br/>Validità {r.proposal.validUntil}</p>{r.proposal.lines.map((l:any,i:number)=><div className="chat-line" key={i}><b>{l.description}</b><span>{l.quantity/100} × {money(l.unitPrice)} netto</span><small>IVA {l.vat/100}% · Sconto {l.discount/100}%</small><strong>{money(l.total)}</strong></div>)}<div className="chat-total"><span>Imponibile {money(r.proposal.net)} · IVA {money(r.proposal.tax)}</span><b>Totale {money(r.proposal.total)}</b></div><p>Conferma entro 15 minuti. Salvi una bozza, senza inviarla al cliente.</p><button disabled={busy} onClick={()=>void confirm(r.proposal.token)}>Conferma e salva bozza</button><button className="secondary" disabled={busy} onClick={()=>setReplies(v=>v.map((item,i)=>i===index?{...item,proposal:undefined,text:'Proposta scartata. Nessun preventivo salvato.'}:item))}>Scarta proposta</button></div>}{r.saved&&<span className="chat-saved">✓ Bozza salvata nei Preventivi</span>}</div></div>)}
 {busy&&<div className="chat-typing" role="status"><i/><i/><i/><span>Sto elaborando…</span></div>}
 </div>
 {replies.length>0&&<div className="chat-shortcuts" aria-label="Consultazioni rapide">{[['context_summary','Questa pagina'],['today_work','Oggi'],['low_balance','Ore residue'],['overdue_invoices','Scadenze'],['pending_jobs','Da approvare']].map(([key,label])=><button className="secondary" key={key} disabled={busy} onClick={()=>void ask(key)}>{label}</button>)}</div>}
 <form className="chat-compose" onSubmit={e=>{e.preventDefault();void ask()}}>
 {status&&!status.enabled&&<p className="chat-hint">Configura l’AI per il testo libero. Le consultazioni rapide sono già disponibili.</p>}
 <div className="chat-input"><textarea ref={composer} aria-label="La tua richiesta" disabled={busy} maxLength={2000} rows={2} required value={message} onChange={e=>setMessage(e.target.value)} placeholder="Scrivi la tua richiesta…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(!busy&&status?.enabled&&consent&&message.trim())void ask()}}}/><button className="chat-send" aria-label="Invia richiesta" disabled={busy||!status?.enabled||!consent||!message.trim()}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 7-7 7 7M12 5v14"/></svg></button></div>
 <label className="chat-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Consento l’invio del testo a OpenRouter e al modello. Uso dati fittizi, senza informazioni riservate.</span></label>
 {error&&<div className="chat-error" role="alert">{error}</div>}
 <div className="chat-footnote"><span>Controlla le proposte prima di confermare.</span><span>luviqAI ✳</span></div>
 </form></section>}
 <button ref={launcher} className={'chat-launcher'+(open?' chat-launcher-open':'')} aria-label={open?'Chiudi assistente AI':'Apri assistente AI'} aria-expanded={open} aria-controls="luviq-chat" onClick={()=>open?close():setOpen(true)}><span className="chat-launch-icon" aria-hidden="true">{open?'×':'✳'}</span><span>{open?'Chiudi':'Chiedi a luviqAI'}</span>{!open&&<i aria-hidden="true"/>}</button>
 </div>;
}
