import React,{useEffect,useState} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {CalendarView,type CalendarIntervention,type CalendarClient,type CalendarUser} from './calendar';
import './calendar.css';

type Session={user:{tenantId:string;role:string};csrf:string};
type State={clients:CalendarClient[];interventions:CalendarIntervention[];team?:CalendarUser[]};
let root:Root|null=null;

function CalendarPortal({close}:{close:()=>void}){
 const [state,setState]=useState<State>({clients:[],interventions:[]}),[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState<CalendarIntervention|null>(null),[busy,setBusy]=useState(false);
 async function load(){const me=await fetch('/api/me');if(!me.ok)throw Error('Accedi per visualizzare il calendario.');const current=await me.json();setSession(current);const res=await fetch('/api/state',{headers:{'X-Tenant-Context':current.user.tenantId}});if(!res.ok)throw Error('Impossibile caricare il calendario.');setState(await res.json())}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const clientName=(id:number)=>state.clients.find(c=>c.id===id)?.name||`Cliente #${id}`;
 const operatorName=(id?:string|null)=>id?(state.team||[]).find(u=>u.id===id)?.name||'Operatore assegnato':'Nessun account assegnato';
 function goInterventions(){close();setTimeout(()=>{const nav=[...document.querySelectorAll('aside nav button')].find(b=>b.textContent?.includes('Interventi')) as HTMLButtonElement|undefined;nav?.click()},50)}
 function prefillDate(value?:string){if(!value)return;setTimeout(()=>{const input=document.querySelector('.overlay input[name="date"]') as HTMLInputElement|null;if(!input)return;const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;setter?.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));input.focus()},220)}
 function newIntervention(date?:string){goInterventions();setTimeout(()=>{const btn=[...document.querySelectorAll('main button')].find(b=>b.textContent?.includes('Nuovo intervento')) as HTMLButtonElement|undefined;btn?.click();prefillDate(date)},150)}
 function hasConflict(item:CalendarIntervention,nextDate:string){if(!item.assignedUserId)return null;const start=new Date(nextDate),end=new Date(start.getTime()+item.duration*60000);return state.interventions.find(other=>other.id!==item.id&&other.status==='planned'&&other.assignedUserId===item.assignedUserId&&start<new Date(new Date(other.date).getTime()+other.duration*60000)&&new Date(other.date)<end)||null}
 async function moveIntervention(item:CalendarIntervention,nextDate:string){if(!session||busy)return false;const conflict=hasConflict(item,nextDate);if(conflict){setError(`${operatorName(item.assignedUserId)} è già impegnato con “${conflict.service}” nello stesso intervallo.`);return false}setBusy(true);setError('');setNotice('');try{const res=await fetch('/api/reschedule',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID(),'X-CSRF-Token':session.csrf,'X-Tenant-Context':session.user.tenantId},body:JSON.stringify({id:item.id,date:nextDate,reason:'Ripianificato dal calendario'})});const result=await res.json();if(!res.ok)throw Error(result.error||'Impossibile ripianificare l’intervento.');await load();setNotice(`Intervento “${item.service}” ripianificato.`);setSelected(null);return true}catch(e:any){setError(e.message);return false}finally{setBusy(false)}}
 return <div className="calendar-portal"><div className="calendar-portal-top"><div><span className="eyebrow">LUVIQAI · GESTIONE OPERATIVA</span><h1>Calendario</h1></div><div className="actions"><button onClick={()=>newIntervention()}>＋ Nuovo intervento</button><button className="secondary" onClick={close}>Chiudi ×</button></div></div>{error&&<div className="alert error calendar-alert">{error}<button className="text" onClick={()=>setError('')}>×</button></div>}{notice&&<div className="alert success calendar-alert">{notice}<button className="text" onClick={()=>setNotice('')}>×</button></div>}{loading?<div className="cal-empty">Caricamento calendario…</div>:<CalendarView items={state.interventions||[]} clients={state.clients||[]} users={state.team||[]} onOpen={setSelected} onNew={newIntervention} onMove={moveIntervention}/>} {selected&&<div className="overlay" onClick={e=>{if(e.target===e.currentTarget&&!busy)setSelected(null)}}><section className="modal calendar-detail" role="dialog" aria-modal="true"><div className="row"><h2>{selected.service}</h2><button className="text" disabled={busy} onClick={()=>setSelected(null)}>×</button></div><p><strong>{clientName(selected.clientId)}</strong></p><p>{new Date(selected.date).toLocaleString('it-IT',{dateStyle:'full',timeStyle:'short'})}</p><p>{selected.team} · {selected.duration} minuti · {selected.operators} operatori</p><p className="muted">Account operatore: {operatorName(selected.assignedUserId)}</p>{selected.notes&&<p>{selected.notes}</p>}<span className={'badge '+selected.status}>{({planned:'Pianificato',pending:'Da approvare',approved:'Approvato',cancelled:'Annullato'} as Record<string,string>)[selected.status]||selected.status}</span><div className="modal-footer"><button className="secondary" disabled={busy} onClick={()=>setSelected(null)}>Chiudi</button>{selected.status==='planned'&&<button className="secondary" disabled={busy} onClick={()=>{const current=new Date(selected.date);const value=`${current.getFullYear()}-${String(current.getMonth()+1).padStart(2,'0')}-${String(current.getDate()).padStart(2,'0')}T${String(current.getHours()).padStart(2,'0')}:${String(current.getMinutes()).padStart(2,'0')}`;goInterventions();setTimeout(()=>{const rows=[...document.querySelectorAll('table tbody tr')];const row=rows.find(r=>r.textContent?.includes(`#${selected.id}`));const button=[...(row?.querySelectorAll('button')||[])].find(b=>b.textContent?.includes('Ripianifica')) as HTMLButtonElement|undefined;button?.click();prefillDate(value)},180)}}>Ripianifica</button>}<button disabled={busy} onClick={goInterventions}>Apri in Interventi</button></div></section></div>}</div>
}

function openCalendar(){if(document.getElementById('calendar-portal-root'))return;const node=document.createElement('div');node.id='calendar-portal-root';document.body.appendChild(node);const close=()=>{root?.unmount();root=null;node.remove()};root=createRoot(node);root.render(<CalendarPortal close={close}/>)}

function installButton(){const nav=document.querySelector('aside nav');if(!nav||nav.querySelector('[data-luviq-calendar]'))return;const button=document.createElement('button');button.dataset.luviqCalendar='1';button.innerHTML='<span>▣</span>Calendario';button.addEventListener('click',openCalendar);const intervention=[...nav.querySelectorAll('button')].find(b=>b.textContent?.includes('Interventi'));if(intervention?.nextSibling)nav.insertBefore(button,intervention.nextSibling);else nav.appendChild(button)}

const observer=new MutationObserver(()=>installButton());observer.observe(document.body,{childList:true,subtree:true});installButton();
