import React,{useMemo,useState} from 'react';
import './calendar.css';

export type CalendarIntervention={id:number;clientId:number;packageId:number;date:string;service:string;team:string;duration:number;operators:number;notes:string;status:string;cost:number;assignedUserId?:string|null};
export type CalendarClient={id:number;name:string};

type View='month'|'week'|'day';
const statusLabel:Record<string,string>={planned:'Pianificato',pending:'Da approvare',approved:'Approvato',cancelled:'Annullato'};
const pad=(n:number)=>String(n).padStart(2,'0');
const ymd=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const startOfWeek=(d:Date)=>{const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x};
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const sameDay=(a:Date,b:Date)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();

export function CalendarView({items,clients,onOpen,onNew}:{items:CalendarIntervention[];clients:CalendarClient[];onOpen:(item:CalendarIntervention)=>void;onNew:(date?:string)=>void}){
 const [view,setView]=useState<View>('month'),[cursor,setCursor]=useState(()=>new Date()),[client,setClient]=useState('all'),[status,setStatus]=useState('all'),[team,setTeam]=useState('all');
 const teams=useMemo(()=>Array.from(new Set(items.map(i=>i.team).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'it')),[items]);
 const filtered=useMemo(()=>items.filter(i=>(client==='all'||String(i.clientId)===client)&&(status==='all'||i.status===status)&&(team==='all'||i.team===team)),[items,client,status,team]);
 const clientName=(id:number)=>clients.find(c=>c.id===id)?.name||`Cliente #${id}`;
 const title=view==='month'?cursor.toLocaleDateString('it-IT',{month:'long',year:'numeric'}):view==='week'?`Settimana ${startOfWeek(cursor).toLocaleDateString('it-IT',{day:'2-digit',month:'short'})} – ${addDays(startOfWeek(cursor),6).toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric'})}`:cursor.toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
 function move(delta:number){const d=new Date(cursor);if(view==='month')d.setMonth(d.getMonth()+delta);else if(view==='week')d.setDate(d.getDate()+7*delta);else d.setDate(d.getDate()+delta);setCursor(d)}
 function eventsFor(day:Date){return filtered.filter(i=>sameDay(new Date(i.date),day)).sort((a,b)=>a.date.localeCompare(b.date))}
 function EventCard({item,compact=false}:{item:CalendarIntervention;compact?:boolean}){const d=new Date(item.date);return <button className={`cal-event ${item.status}`} onClick={()=>onOpen(item)} title={`${clientName(item.clientId)} · ${item.service}`}><span>{d.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</span><strong>{item.service}</strong>{!compact&&<small>{clientName(item.clientId)} · {item.team}</small>}</button>}
 function Month(){const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),start=startOfWeek(first),days=Array.from({length:42},(_,i)=>addDays(start,i));return <div className="cal-month"><div className="cal-weekdays">{['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map(x=><b key={x}>{x}</b>)}</div><div className="cal-grid">{days.map(day=>{const outside=day.getMonth()!==cursor.getMonth(),ev=eventsFor(day);return <div className={`cal-day ${outside?'outside':''} ${sameDay(day,new Date())?'today':''}`} key={ymd(day)}><button className="cal-date" onClick={()=>{setCursor(day);setView('day')}}>{day.getDate()}</button><div className="cal-day-events">{ev.slice(0,3).map(i=><EventCard key={i.id} item={i} compact/>)}{ev.length>3&&<button className="cal-more" onClick={()=>{setCursor(day);setView('day')}}>+{ev.length-3} altri</button>}</div></div>})}</div></div>}
 function Week(){const start=startOfWeek(cursor),days=Array.from({length:7},(_,i)=>addDays(start,i));return <div className="cal-week">{days.map(day=><section className={`cal-week-day ${sameDay(day,new Date())?'today':''}`} key={ymd(day)}><header><span>{day.toLocaleDateString('it-IT',{weekday:'short'})}</span><b>{day.getDate()}</b></header><div>{eventsFor(day).map(i=><EventCard key={i.id} item={i}/>)}</div><button className="cal-add-inline" onClick={()=>onNew(`${ymd(day)}T09:00`)}>＋ Aggiungi</button></section>)}</div>}
 function Day(){const ev=eventsFor(cursor);return <div className="cal-day-view"><div className="cal-day-head"><div><span>{cursor.toLocaleDateString('it-IT',{weekday:'long'})}</span><strong>{cursor.getDate()}</strong></div><button onClick={()=>onNew(`${ymd(cursor)}T09:00`)}>＋ Nuovo intervento</button></div>{ev.length?<div className="cal-agenda">{ev.map(i=><EventCard key={i.id} item={i}/>)}</div>:<div className="cal-empty">Nessun intervento pianificato per questa giornata.</div>}</div>}
 return <section className="calendar-shell"><div className="cal-toolbar"><div className="cal-nav"><button className="secondary" onClick={()=>move(-1)}>←</button><button className="secondary" onClick={()=>setCursor(new Date())}>Oggi</button><button className="secondary" onClick={()=>move(1)}>→</button><h2>{title}</h2></div><div className="cal-views">{(['month','week','day'] as View[]).map(v=><button key={v} className={view===v?'selected':'secondary'} onClick={()=>setView(v)}>{v==='month'?'Mese':v==='week'?'Settimana':'Giorno'}</button>)}</div></div><div className="cal-filters"><label>Cliente<select value={client} onChange={e=>setClient(e.target.value)}><option value="all">Tutti</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Squadra / operatore<select value={team} onChange={e=>setTeam(e.target.value)}><option value="all">Tutti</option>{teams.map(t=><option key={t} value={t}>{t}</option>)}</select></label><label>Stato<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tutti</option>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><span className="cal-count">{filtered.length} interventi</span></div>{view==='month'?<Month/>:view==='week'?<Week/>:<Day/>}</section>
}
