import React,{useEffect,useState} from 'react';
import {Session,post} from './access';

const money=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n/100);
const labels:Record<string,string>={queued:'In coda',sending:'Invio in corso',sent:'Accettata dal server email',preview:'Simulazione pronta',uncertain:'Da verificare',cancelled:'Tentativo chiuso'};
export function MailCenter({session,onChanged}:{session:Session;onChanged:()=>Promise<void>}){
 const [data,setData]=useState<any>(null),[detail,setDetail]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[closing,setClosing]=useState<any>(null);
 async function get(path:string){const r=await fetch('/api/'+path,{headers:{'X-Tenant-Context':session.user.tenantId}});const json=await r.json();if(!r.ok)throw Error(json.error);return json;}
 async function refresh(){setData(await get('mail'));}
 useEffect(()=>{refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),5000);return()=>clearInterval(timer)},[]);
 async function mark(id:string){setBusy(true);setError('');try{await post('notification-read',{id},session.csrf,session.user.tenantId);await refresh();await onChanged();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="mail-center">{error&&<div className="alert error" role="alert">{error}</div>}{!data?<p>Caricamento email e notifiche…</p>:<>
 <div className="alert">{data.mode==='preview'?<><b>Simulazione locale: nessuna email viene spedita.</b><p>Mittente previsto: {data.from}</p><p>Controlla il messaggio e prova la pagina cliente. I collegamenti localhost funzionano soltanto su questo computer.</p></>:<><b>Invio SMTP attivo</b><p>Mittente: {data.from}. L’esito “accettata dal server” non garantisce la lettura o l’arrivo nella posta in entrata.</p></>}</div>
 <h2>Risposte dei clienti</h2>{data.notifications.length?data.notifications.map((n:any)=><article className="notification-card" key={n.id}><div><span className={'badge '+(n.readAt?'':'pending')}>{n.readAt?'Letta':'Nuova'}</span><h3>{n.title}</h3><p>{n.body}</p><small>{new Date(n.created).toLocaleString('it-IT')}</small></div>{!n.readAt&&<button className="secondary" disabled={busy} onClick={()=>void mark(n.id)}>Segna come letta</button>}</article>):<div className="empty"><p>Le risposte ai preventivi compariranno qui e aggiorneranno automaticamente lo stato della proposta.</p></div>}
 <h2>Email preparate e invii</h2>{data.messages.length?<div className="client-grid">{data.messages.map((m:any)=><article className="client-card" key={m.id}><span className={'badge '+(m.status==='uncertain'?'low':m.status==='preview'?'pending':'approved')}>{labels[m.status]}</span><h3>{m.subject}</h3><p>A: {m.recipient}</p><small>{new Date(m.created).toLocaleString('it-IT')}</small>{m.error&&<p className="danger">{m.error}</p>}<div className="actions"><button className="secondary" onClick={()=>get('mail/'+m.id).then(setDetail).catch(e=>setError(e.message))}>Apri email</button>{['uncertain','queued'].includes(m.status)&&<button className="text danger" onClick={()=>setClosing(m)}>Chiudi tentativo</button>}</div></article>)}</div>:<div className="empty"><p>Apri un preventivo e scegli “Invia via email” per preparare il primo messaggio.</p></div>}
 </>}{detail&&<div className="overlay"><section className="modal mail-preview" role="dialog" aria-modal="true" aria-labelledby="mail-title"><div className="row"><h2 id="mail-title">Anteprima email</h2><button className="text" aria-label="Chiudi anteprima" onClick={()=>setDetail(null)}>×</button></div><h3>{detail.subject}</h3><p>A: {detail.recipient}</p><span className="badge">{labels[detail.status]}</span><pre>{detail.content.text}</pre><p>Allegati: {detail.content.attachments.map((a:any)=>a.filename).join(', ')||'Nessuno'}</p><div className="actions">{detail.content.link&&['sent','preview'].includes(detail.status)&&<a className="button" href={detail.content.link} target="_blank" rel="noreferrer">Apri pagina cliente</a>}<a className="button secondary" href={'/api/mail/'+detail.id+'/eml?company='+encodeURIComponent(session.user.tenantId)}>Scarica email con allegati (.eml)</a></div></section></div>}
 {closing&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true"><h2>Chiudi tentativo di invio</h2><p>Controlla prima la casella del mittente: il messaggio potrebbe essere stato consegnato. Il collegamento di questo tentativo verrà disattivato. Potrai poi preparare una nuova email.</p><form onSubmit={async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');setBusy(true);try{await post('mail-cancel',{id:closing.id,reason},session.csrf,session.user.tenantId);setClosing(null);await refresh();await onChanged();}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><label>Motivazione *<textarea name="reason" required maxLength={2000}/></label><div className="actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setClosing(null)}>Indietro</button><button disabled={busy}>Conferma chiusura</button></div></form></section></div>}
 </section>;
}

export function QuoteResponse({token,initialDecision}:{token:string;initialDecision?:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[decision,setDecision]=useState(['accepted','rejected'].includes(initialDecision||'')?initialDecision!:''),[busy,setBusy]=useState(false);
 async function refresh(){const r=await fetch('/api/public/quotes/'+encodeURIComponent(token));const j=await r.json();if(!r.ok)throw Error(j.error);setData(j);}
 useEffect(()=>{document.title='Rispondi al preventivo';refresh().catch(e=>setError(e.message));},[token]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await fetch('/api/public/quotes/'+encodeURIComponent(token),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),notes:form.get('notes'),decision,confirm:form.get('confirm')==='on'})});const j=await r.json();if(!r.ok)throw Error(j.error);await refresh();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="customer-response"><div className="customer-paper">{data?<>
 {data.mode==='preview'&&<div className="alert"><b>Prova locale</b> · Questo collegamento proviene da un’email simulata.</div>}
 <div className="response-brand">{data.company.logoData&&<img src={data.company.logoData} alt="Logo aziendale"/>}<h2>{data.company.name}</h2><p>{data.company.email} {data.company.phone}</p></div><div className="eyebrow">PREVENTIVO {data.number}</div><h1>{data.title}</h1><p>Riservato a {data.clientName} · Valido fino al {data.validUntil.split('-').reverse().join('/')}</p><div className="quote-totals"><p>Imponibile <strong>{money(data.net)}</strong></p><p>IVA <strong>{money(data.tax)}</strong></p><p className="quote-total">Totale <strong>{money(data.total)}</strong></p></div>
 <a className="button secondary" href={'/api/public/quotes/'+encodeURIComponent(token)+'/pdf'}>Scarica preventivo PDF</a>
 {data.terms&&<><h3>Condizioni</h3><p className="response-notes">{data.terms}</p></>}{data.notes&&<><h3>Note della proposta</h3><p className="response-notes">{data.notes}</p></>}
 {data.response?<div className="alert success" role="status"><h2>Risposta registrata</h2><p>Hai {data.response.decision==='accepted'?'accettato':'rifiutato'} il preventivo. L’impresa è stata avvisata.</p>{data.response.notes&&<p>Le tue note: {data.response.notes}</p>}<p>Per eventuali modifiche contatta direttamente l’impresa.</p></div>:data.expired?<div className="alert">Questo preventivo è scaduto. Contatta l’impresa per una nuova proposta.</div>:<form onSubmit={submit}><h2>La tua risposta</h2><p>Leggi il PDF e le condizioni prima di confermare la scelta.</p><label>Nome e cognome *<input name="name" required maxLength={150} disabled={busy}/></label><label>Note per l’impresa<textarea name="notes" maxLength={2000} disabled={busy} placeholder="Aggiungi richieste, chiarimenti o il motivo del rifiuto"/></label><div className="actions"><button type="button" aria-pressed={decision==='accepted'} className={decision==='accepted'?'':'secondary'} disabled={busy} onClick={()=>setDecision('accepted')}>Accetto il preventivo</button><button type="button" aria-pressed={decision==='rejected'} className={decision==='rejected'?'danger':'secondary'} disabled={busy} onClick={()=>setDecision('rejected')}>Rifiuto il preventivo</button></div>{decision&&<><div className="alert">Stai per {decision==='accepted'?'accettare':'rifiutare'} il preventivo {data.number}, totale {money(data.total)}.</div><label className="checkbox"><input name="confirm" type="checkbox" required disabled={busy}/> Confermo di aver letto il preventivo e di voler comunicare questa scelta all’impresa.</label><button disabled={busy} type="submit">{busy?'Registrazione…':'Conferma e invia risposta'}</button></>}</form>}
 </>:!error?<p>Caricamento del preventivo…</p>:null}{error&&<div className="alert error" role="alert">{error}</div>}<footer>Un servizio realizzato da luviqAI · Collegamento personale</footer></div></div>;
}
