import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import './style.css';
type Client={id:number;name:string;email:string;phone:string;address:string};
type Package={id:number;clientId:number;tier:string;original:number;initial:number;rule:string;paid:number;consumed:number;remaining:number;committed:number;free:number;renewedFrom:number|null};
type Intervention={id:number;clientId:number;packageId:number;date:string;service:string;team:string;duration:number;operators:number;notes:string;status:string;cost:number};
type Audit={id:number;date:string;author:string;action:string;clientId:number;interventionId:number;beforeValue:string;afterValue:string;reason:string};
type State={clients:Client[];packages:Package[];interventions:Intervention[];audit:Audit[]};
const hours=(v:number)=>`${(v/60).toLocaleString('it-IT',{maximumFractionDigits:2})} h`;
const date=(s:string)=>new Date(s).toLocaleString('it-IT',{dateStyle:'short',timeStyle:'short'});
const labels:Record<string,string>={planned:'Pianificato',pending:'Da approvare',approved:'Approvato',cancelled:'Annullato',client:'Cliente salvato',package:'Pacchetto creato',pay:'Pagamento confermato',intervention:'Intervento inserito',complete:'Intervento completato',approve:'Intervento approvato',rectify:'Intervento rettificato',cancel:'Intervento annullato',seed:'Demo inizializzata'};
const sections=['Panoramica','Clienti','Pacchetti ore','Interventi','Storico attività'];
function App(){
const[state,setState]=useState<State>({clients:[],packages:[],interventions:[],audit:[]}),[page,setPage]=useState('Panoramica'),[search,setSearch]=useState(''),[clientId,setClientId]=useState<number|null>(null),[modal,setModal]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[filter,setFilter]=useState('all');
async function refresh(){const res=await fetch('/api/state');if(!res.ok)throw Error('Impossibile caricare i dati.');setState(await res.json());setLoaded(true)}
useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
const name=(id:number)=>state.clients.find(c=>c.id===id)?.name||'Sistema';
const pack=(id:number)=>state.packages.find(p=>p.id===id)!;
function open(kind:string,values:any={}){setError('');setModal({kind,key:crypto.randomUUID(),...values})}
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=Object.fromEntries(new FormData(e.currentTarget));let input:any={...form};const kind=modal.kind;
if(kind==='client'&&modal.item)input.id=modal.item.id;
if(kind==='package'){input.paid=form.paid==='on';input.renewedFrom=modal.item?.id||null}
if(['pay','complete','approve','rectify','cancel'].includes(kind))input.id=modal.item.id;
setBusy(true);setError('');try{const res=await fetch('/api/'+kind,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':modal.key},body:JSON.stringify(input)});const result=await res.json();if(!res.ok){setModal({...modal,key:crypto.randomUUID()});throw Error(result.error)}await refresh();setModal(null);setNotice('Operazione salvata. Saldi e storico aggiornati.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
const paid=state.packages.filter(p=>p.paid&&p.remaining>0),pending=state.interventions.filter(i=>i.status==='pending'),low=state.packages.filter(p=>p.paid&&p.remaining<=300),upcoming=state.interventions.filter(i=>i.status==='planned'&&new Date(i.date)>new Date()).sort((a,b)=>a.date.localeCompare(b.date));
function packageCards(list:Package[]){return list.length?<div className="package-grid">{list.map(p=><article className="package" key={p.id}><div className="row"><span className={'tier '+p.tier.toLowerCase()}>{p.tier==='Star'?'✦':p.tier==='Love'?'♡':'♛'} {p.tier}</span><span className={'badge '+(!p.paid?'pending':p.remaining<=300?'low':'approved')}>{!p.paid?'Pagamento da confermare':p.remaining===0?'Esaurito':p.remaining<=300?'Saldo basso':'Attivo'}</span></div><h3>{name(p.clientId)}</h3><p>Pacchetto #{p.id} · taglio {hours(p.original)} {p.renewedFrom&&`· rinnovo #${p.renewedFrom}`}</p><div className="balance">{hours(p.remaining)} <small>residue</small></div><div className="progress"><span style={{width:`${p.remaining/p.initial*100}%`}}/></div><div className="balances"><div>Iniziali<strong>{hours(p.initial)}</strong></div><div>Consumate<strong>{hours(p.consumed)}</strong></div><div>Impegnate<strong>{hours(p.committed)}</strong></div><div>Libere<strong>{hours(p.free)}</strong></div></div><p>Conteggio per {p.rule==='operator'?'operatore':'squadra'}</p><div className="actions">{!p.paid&&<button onClick={()=>open('pay',{item:p})}>Conferma pagamento</button>}<button className="secondary" onClick={()=>open('package',{item:p})}>Rinnova</button></div></article>)}</div>:<Empty text="Nessun pacchetto presente. Crea un pacchetto e associalo a un cliente."/>}
function interventionTable(list:Intervention[]){return list.length?<div className="table-wrap"><table><thead><tr><th>Cliente / servizio</th><th>Appuntamento</th><th>Durata e squadra</th><th>Ore conteggiate</th><th>Stato</th><th>Azioni</th></tr></thead><tbody>{list.map(i=><tr key={i.id}><td><strong>{name(i.clientId)}</strong><span>{i.service} · #{i.id}</span>{i.notes&&<small>{i.notes}</small>}</td><td>{date(i.date)}<span>{pack(i.packageId)?.tier} #{i.packageId}</span></td><td>{i.duration} min × {i.operators} op.<span>{i.team}</span></td><td><strong>{hours(i.cost)}</strong><small>per {pack(i.packageId)?.rule==='operator'?'operatore':'squadra'}</small></td><td><span className={'badge '+i.status}>{labels[i.status]}</span></td><td><div className="actions">{i.status==='planned'&&<button disabled={new Date(i.date)>new Date()} title="Disponibile dalla data dell’intervento" onClick={()=>open('complete',{item:i})}>Completa</button>}{i.status==='pending'&&<button onClick={()=>open('approve',{item:i})}>Approva</button>}{i.status==='approved'&&<button className="secondary" onClick={()=>open('rectify',{item:i})}>Rettifica</button>}{i.status!=='cancelled'&&<button className="text danger" onClick={()=>open('cancel',{item:i})}>Annulla</button>}</div></td></tr>)}</tbody></table></div>:<Empty text="Nessun intervento da mostrare. I nuovi appuntamenti compariranno qui."/>}
function history(list:Audit[]){return list.length?<div className="history">{list.map(a=><article key={a.id}><div className="history-dot"/><div><strong>{labels[a.action]||a.action}</strong><p>{date(a.date)} · {a.author} · {name(a.clientId)}{a.interventionId?` · intervento #${a.interventionId}`:''}</p>{a.reason&&<p>{a.reason}</p>}<details><summary>Valori precedenti e nuovi</summary><div className="audit-values"><div><b>Prima</b><pre>{JSON.stringify(JSON.parse(a.beforeValue),null,2)}</pre></div><div><b>Dopo</b><pre>{JSON.stringify(JSON.parse(a.afterValue),null,2)}</pre></div></div></details></div></article>)}</div>:<Empty text="Nessuna attività registrata per questo cliente."/>}
const selected=state.clients.find(c=>c.id===clientId);
return <><aside><a className="brand" href="#" onClick={e=>e.preventDefault()}><span className="brand-icon">✳</span><div>my clean<small>MULTISERVICE</small></div></a><div className="workspace">GESTIONE OPERATIVA</div><nav>{sections.map((s,index)=><button key={s} className={page===s?'active':''} onClick={()=>{setPage(s);setClientId(null);setSearch('');setFilter('all')}}><span>{['◫','♧','▱','▦','◷'][index]}</span>{s}{s==='Interventi'&&pending.length>0&&<b>{pending.length}</b>}</button>)}</nav><div className="sidebar-bottom"><span className="avatar">RL</span><div>Responsabile locale<small>Demo · accesso unico</small></div></div><footer>Realizzata da <strong>luviqAI</strong></footer></aside>
<main><div className="topbar"><span>My Clean <b>/</b> Pacchetti ore</span><span className="local"><i/> Demo locale</span></div><div className="content"><header><div><div className="eyebrow">MY CLEAN · PACCHETTI ORE</div><h1>{selected?selected.name:page}</h1><p>{selected?'Scheda cliente e riepilogo completo.':({Panoramica:'Ogni ora sotto controllo, ogni cliente al centro.',Clienti:'Contatti, pacchetti e attività in un unico posto.','Pacchetti ore':'Disponibilità trasparente, dal pagamento al rinnovo.',Interventi:'Pianifica il lavoro. Verifica le ore. Approva con sicurezza.','Storico attività':'Ogni variazione resta tracciata e verificabile.'} as any)[page]}</p></div><div className="actions">{page==='Clienti'&&!selected&&<button onClick={()=>open('client')}>＋ Nuovo cliente</button>}{page==='Pacchetti ore'&&<button onClick={()=>open('package')}>＋ Nuovo pacchetto</button>}{['Panoramica','Interventi'].includes(page)&&<button onClick={()=>open('intervention')}>＋ Nuovo intervento</button>}{page==='Storico attività'&&<a className="button" href="/api/export">↓ Esporta CSV</a>}</div></header>
{error&&!modal&&<div role="alert" className="alert error">{error} <button onClick={()=>refresh().catch(e=>setError(e.message))}>Riprova</button></div>}{notice&&<div className="alert success" role="status">{notice}<button className="text" onClick={()=>setNotice('')}>×</button></div>}
{!loaded?<Empty text="Caricamento dei dati…"/>:<>
{page==='Panoramica'&&<><div className="hero"><div><span className="eyebrow">IL TEMPO, GESTITO BENE</span><h2>Più cura per i clienti.<br/>Meno pensieri sulle ore.</h2><p>Una visione chiara di disponibilità e lavoro in programma.</p></div><div className="hero-mark">✳</div></div><div className="stats"><Metric label="Ore residue pagate" value={hours(paid.reduce((s,p)=>s+p.remaining,0))} hint="Saldo disponibile prima degli impegni"/><Metric label="Pacchetti attivi" value={String(paid.length)} hint="Pagati e con ore residue"/><Metric label="Da approvare" value={String(pending.length)} hint="Interventi in attesa di verifica"/><Metric label="Saldo basso" value={String(low.length)} hint="Pacchetti con 5 ore o meno"/></div><div className="section-title"><h2>Prossimi interventi</h2><button className="text" onClick={()=>setPage('Interventi')}>Vedi tutti →</button></div>{interventionTable(upcoming.slice(0,4))}<div className="section-title"><h2>Da tenere d’occhio</h2><span>Rinnovi e pagamenti</span></div>{packageCards(state.packages.filter(p=>!p.paid||p.remaining<=300))}<div className="demo-note">Dati dimostrativi: i quattro clienti iniziali sono fittizi. Nessun pagamento o messaggio viene inviato.</div></>}
{page==='Clienti'&&(!selected?<><input className="search" aria-label="Cerca cliente" placeholder="⌕  Cerca un cliente per nome…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="client-grid">{state.clients.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())).map(c=><article className="client-card" key={c.id}><span className="client-avatar">{c.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span><h3>{c.name}</h3><p>{c.email||'Email non inserita'}</p><p>{c.address||'Indirizzo non inserito'}</p><div className="row"><span>{state.packages.filter(p=>p.clientId===c.id).length} pacchetti</span><button className="secondary" onClick={()=>setClientId(c.id)}>Apri scheda →</button></div></article>)}</div>{!state.clients.some(c=>c.name.toLowerCase().includes(search.toLowerCase()))&&<Empty text="Nessun cliente trovato. Prova un altro nome oppure crea un nuovo cliente."/>}</>:<><div className="actions no-print"><button className="secondary" onClick={()=>setClientId(null)}>← Tutti i clienti</button><button onClick={()=>open('client',{item:selected})}>Modifica cliente</button><button className="secondary" onClick={()=>window.print()}>Stampa riepilogo</button><button className="secondary" onClick={()=>open('package',{clientId:selected.id})}>＋ Pacchetto</button></div><div className="contact-panel">{selected.email||'Email non inserita'} · {selected.phone||'Telefono non inserito'}<p>{selected.address||'Indirizzo non inserito'}</p><small>Riepilogo al {new Date().toLocaleString('it-IT')} · realizzata da luviqAI</small></div><h2>Pacchetti ore</h2>{packageCards(state.packages.filter(p=>p.clientId===clientId))}<h2>Interventi</h2>{interventionTable(state.interventions.filter(i=>i.clientId===clientId))}<h2>Storico cliente</h2>{history(state.audit.filter(a=>a.clientId===clientId))}</>)}
{page==='Pacchetti ore'&&packageCards(state.packages)}
{page==='Interventi'&&<><div className="filters">{['all','planned','pending','approved','cancelled'].map(s=><button className={filter===s?'selected':'secondary'} onClick={()=>setFilter(s)} key={s}>{s==='all'?'Tutti':labels[s]}</button>)}</div>{interventionTable(state.interventions.filter(i=>filter==='all'||i.status===filter))}<p className="muted">Gli appuntamenti futuri si possono completare a partire dalla data e dall’ora pianificate.</p></>}
{page==='Storico attività'&&history(state.audit)}
</>}<div className="page-footer">My Clean · Pacchetti ore <span>Realizzata da luviqAI</span></div></div></main>
{modal&&<div className="overlay" onClick={e=>{if(e.target===e.currentTarget&&!busy)setModal(null)}}><section role="dialog" aria-modal="true" aria-labelledby="modal-title" className="modal"><div className="row"><h2 id="modal-title">{({client:modal.item?'Modifica cliente':'Nuovo cliente',package:modal.item?'Rinnova pacchetto':'Nuovo pacchetto',intervention:'Nuovo intervento',pay:'Conferma pagamento',approve:'Approva intervento',complete:'Completa intervento',rectify:'Rettifica intervento',cancel:'Annulla intervento'} as any)[modal.kind]}</h2><button disabled={busy} className="text" aria-label="Chiudi" onClick={()=>setModal(null)}>×</button></div><form onSubmit={submit}>
{modal.kind==='client'&&<>{['name','email','phone','address'].map((field,index)=><label key={field}>{['Nome cliente *','Email','Telefono','Indirizzo'][index]}<input autoFocus={index===0} name={field} type={field==='email'?'email':'text'} required={index===0} maxLength={field==='name'?300:500} defaultValue={modal.item?.[field]||''}/></label>)}</>}
{modal.kind==='package'&&<><label>Cliente *<select name="clientId" required defaultValue={modal.item?.clientId||modal.clientId||''}><option value="" disabled>Seleziona cliente</option>{state.clients.filter(c=>!modal.item||c.id===modal.item.clientId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Taglio originario<select name="tier" defaultValue={modal.tier||modal.item?.tier||'Star'} onChange={e=>setModal({...modal,tier:e.target.value})}>{['Star','Love','Luxury'].map((t,i)=><option key={t} value={t}>{t} · {[20,40,60][i]} ore</option>)}</select></label><label>Saldo iniziale in minuti *<input key={modal.tier} name="initial" type="number" min="1" max={({Star:1200,Love:2400,Luxury:3600} as any)[modal.tier||modal.item?.tier||'Star']} defaultValue={({Star:1200,Love:2400,Luxury:3600} as any)[modal.tier||modal.item?.tier||'Star']} required/></label><p className="help">Per importare un pacchetto parzialmente usato, inserisci i minuti rimasti. Il taglio originario viene conservato.</p><label>Regola di conteggio (non modificabile)<select name="rule" defaultValue={modal.item?.rule||'operator'}><option value="operator">Per operatore · 2 persone × 2 h = 4 h</option><option value="team">Per squadra · 2 persone × 2 h = 2 h</option></select></label><label className="checkbox"><input name="paid" type="checkbox"/> Confermo che il pagamento è stato ricevuto</label>{modal.item&&<div className="alert">Verrà creato un nuovo pacchetto. Il precedente e tutti i suoi movimenti rimangono nello storico.</div>}</>}
{modal.kind==='intervention'&&<><label>Cliente *<select required value={modal.clientId||''} onChange={e=>setModal({...modal,clientId:Number(e.target.value),packageId:''})}><option value="" disabled>Seleziona cliente</option>{state.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Pacchetto pagato *<select name="packageId" value={modal.packageId||''} required onChange={e=>setModal({...modal,packageId:Number(e.target.value)})}><option value="" disabled>Seleziona pacchetto</option>{state.packages.filter(p=>p.clientId===modal.clientId&&p.paid).map(p=><option key={p.id} value={p.id}>{p.tier} #{p.id} · {hours(p.free)} libere</option>)}</select></label>{modal.clientId&&!state.packages.some(p=>p.clientId===modal.clientId&&p.paid)?<p className="help">Questo cliente non ha pacchetti pagati. Conferma prima il pagamento nella sezione Pacchetti ore.</p>:null}<label>Data e ora *<input name="date" type="datetime-local" required/></label><label>Servizio *<input name="service" required maxLength={300} placeholder="Es. Pulizia ordinaria"/></label><label>Operatore o squadra *<input name="team" required maxLength={300}/></label><Duration/><label>Stato iniziale<select name="status"><option value="planned">Pianificato</option><option value="pending">Da approvare (già effettuato)</option></select></label><label>Note<textarea name="notes" maxLength={3000}/></label><p className="help">Le ore vengono impegnate subito. L’addebito avviene solo dopo l’approvazione.</p></>}
{['complete','rectify'].includes(modal.kind)&&<><p>{modal.item.service} · {name(modal.item.clientId)}</p><Duration item={modal.item}/><p className="help">Conteggio per {pack(modal.item.packageId).rule==='operator'?'operatore':'squadra'}. Disponibilità massima per questa attività: {hours(pack(modal.item.packageId).free+modal.item.cost)}.</p>{modal.kind==='complete'&&<div className="alert">Inserisci la durata effettiva. L’intervento passerà da pianificato a da approvare.</div>}</>}
{modal.kind==='approve'&&<><p>{modal.item.service} · {name(modal.item.clientId)}</p><div className="approval"><div>Ore da scalare<strong>{hours(modal.item.cost)}</strong></div><div>Saldo attuale<strong>{hours(pack(modal.item.packageId).remaining)}</strong></div><div>Saldo dopo l’approvazione<strong>{hours(pack(modal.item.packageId).remaining-modal.item.cost)}</strong></div></div><p>L’approvazione registra l’addebito e conserva l’operazione nello storico.</p></>}
{modal.kind==='pay'&&<p>Confermi di aver ricevuto il pagamento del pacchetto {modal.item.tier} #{modal.item.id} di {name(modal.item.clientId)}? Sarà possibile inserire interventi.</p>}
{modal.kind==='cancel'&&<p>{modal.item.status==='approved'?`Verranno restituite ${hours(modal.item.cost)} al saldo.`:`Verranno liberate ${hours(modal.item.cost)} impegnate.`} L’intervento rimarrà nello storico come annullato.</p>}
{['rectify','cancel'].includes(modal.kind)&&<label>Motivazione obbligatoria<textarea name="reason" required minLength={1} maxLength={2000} placeholder="Descrivi il motivo della modifica"/></label>}
{error&&<div role="alert" className="alert error">{error}</div>}<div className="modal-footer"><button type="button" className="secondary" disabled={busy} onClick={()=>setModal(null)}>Indietro</button><button disabled={busy} type="submit">{busy?'Salvataggio…':['approve','pay','cancel','rectify'].includes(modal.kind)?'Conferma operazione':'Salva'}</button></div></form></section></div>}
</>}
function Duration({item}:{item?:Intervention}){return <div className="form-grid"><label>Durata in minuti *<input name="duration" type="number" min="1" max="3600" step="1" required defaultValue={item?.duration||120}/></label><label>Numero operatori *<input name="operators" type="number" min="1" max="100" step="1" required defaultValue={item?.operators||1}/></label></div>}
function Empty({text}:{text:string}){return <div className="empty"><span>◇</span><p>{text}</p></div>}
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>}
createRoot(document.getElementById('root')!).render(<App/>);

