import React,{useEffect,useState} from 'react';
import {Session} from './access';
import './operations.css';
const euro=(n:number)=>(n/100).toLocaleString('it-IT',{style:'currency',currency:'EUR'});
const localDay=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const hours=(n:number)=>(n/60).toLocaleString('it-IT',{maximumFractionDigits:2})+' h';
const weekdays=['Lun','Mar','Mer','Gio','Ven','Sab','Dom'];
type Props={state:any;session:Session;onSaved:()=>Promise<void>;navigate:(page:string)=>void};
export function Operations({state,session,onSaved,navigate}:Props){
  const [form,setForm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selectedQuote,setSelectedQuote]=useState('');
  async function save(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();if(busy)return;const el=e.currentTarget,values=new FormData(el),input:any=Object.fromEntries(values);let action=form;
    if(form==='recurrence')input.weekdays=values.getAll('weekdays').map(Number);
    if(form==='team')input.active=values.get('active')==='on';
    if(form==='quote-convert'){
      const q=state.quotes.find((x:any)=>x.id===Number(input.quoteId)),m=state.catalog.find((x:any)=>x.id===Number(input.templateId));
      input.revision=q?.revision;input.templateRevision=m?.revision;
    }
    setBusy(true);setError('');
    try{const res=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':el.dataset.key||'','X-CSRF-Token':session.csrf,'X-Tenant-Context':session.user.tenantId},body:JSON.stringify(input)});const result=await res.json();if(!res.ok)throw Error(result.error);await onSaved();setForm('');setNotice('Operazione salvata.');}catch(e:any){setError(e.message)}finally{setBusy(false)}
  }
  const clientName=(id:number)=>state.clients.find((c:any)=>c.id===id)?.name||'Cliente';
  const availableQuotes=state.quotes.filter((q:any)=>q.status==='accepted'&&!state.packages.some((p:any)=>p.sourceQuoteId===q.id));
  return <section><div className="actions"><button onClick={()=>{setForm('recurrence');setError('')}}>＋ Serie di interventi</button><button className="secondary" onClick={()=>{setForm('quote-convert');setError('')}}>Converti preventivo</button><button className="secondary" onClick={()=>{setForm('team');setError('')}}>＋ Squadra</button><button className="secondary" onClick={()=>{setForm('recurrence-cancel');setError('')}}>Annulla serie</button></div>
    <p className="muted">Le serie usano il fuso Europe/Rome e compaiono nel Calendario esistente. Per completare, approvare o ripianificare un appuntamento apri Interventi.</p>
    {notice&&<p role="status">{notice}</p>}
    {form&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="ops-title"><div className="row"><h2 id="ops-title">{({'recurrence':'Serie di interventi','quote-convert':'Converti preventivo','team':'Nuova squadra','recurrence-cancel':'Annulla serie'} as any)[form]}</h2><button className="text" disabled={busy} onClick={()=>setForm('')} aria-label="Chiudi">×</button></div><OperationForm key={form} save={save}>
      {form==='team'&&<><label>Nome squadra<input name="name" required maxLength={120}/></label><label><input type="checkbox" name="active" defaultChecked/> Attiva</label></>}
      {form==='quote-convert'&&<><p>Il preventivo accettato viene collegato a un solo pacchetto del catalogo. Non vengono registrati pagamenti né create fatture. Conferma che il modello scelto corrisponda al servizio concordato.</p><label>Preventivo<select name="quoteId" required value={selectedQuote} onChange={e=>setSelectedQuote(e.target.value)}><option value="">Seleziona</option>{availableQuotes.map((q:any)=><option key={q.id} value={q.id}>{q.number} · {clientName(q.clientId)} · {euro(q.total)}</option>)}</select></label><label>Modello pacchetto<select name="templateId" required><option value="">Seleziona</option>{state.catalog.filter((t:any)=>t.active).map((t:any)=><option key={t.id} value={t.id}>{t.name} · {hours(t.minutes)} · {t.rule==='operator'?'per operatore':'per squadra'}</option>)}</select></label><label>Motivazione<textarea name="reason" required maxLength={2000}/></label><label><input type="checkbox" required/> Confermo l’abbinamento; il pacchetto sarà non pagato.</label></>}
      {form==='recurrence'&&<><label>Pacchetto pagato<select name="packageId" required><option value="">Seleziona</option>{state.packages.filter((p:any)=>p.paid&&p.free>0).map((p:any)=><option key={p.id} value={p.id}>{clientName(p.clientId)} · {p.tier} #{p.id} · {hours(p.free)} libere</option>)}</select></label><div className="form-grid"><label>Data iniziale<input name="startDate" type="date" required min={localDay(new Date())}/></label><label>Ora (Roma)<input name="localTime" type="time" required/></label></div><fieldset><legend>Giorni della settimana</legend><div className="ops-weekdays">{weekdays.map((d,i)=><label key={d}><input type="checkbox" name="weekdays" value={i+1}/>{d}</label>)}</div></fieldset><div className="form-grid"><label>Frequenza<select name="frequencyWeeks"><option value="1">Ogni settimana</option><option value="2">Ogni due settimane</option></select></label><label>Numero totale appuntamenti<input name="occurrenceCount" type="number" min={1} max={52} required defaultValue={4}/></label></div><label>Squadra<select name="teamId" required><option value="">Seleziona</option>{state.teams.filter((t:any)=>t.active).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Account operatore<select name="assignedUserId"><option value="">Nessuno</option>{(state.team||[]).filter((u:any)=>u.active&&u.role==='operator').map((u:any)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Servizio<input name="service" required maxLength={300}/></label><div className="form-grid"><label>Minuti per appuntamento<input type="number" name="duration" min={1} max={3600} defaultValue={60} required/></label><label>Numero operatori<input type="number" name="operators" min={1} max={100} defaultValue={1} required/></label></div><p>La serie impegna subito tutte le ore. Saldo insufficiente, sovrapposizioni o orari ambigui bloccano l’intera operazione.</p></>}
      {form==='recurrence-cancel'&&<><label>Serie<select name="id" required><option value="">Seleziona</option>{state.recurrenceSeries.filter((r:any)=>r.active).map((r:any)=><option key={r.id} value={r.id}>{clientName(r.clientId)} · {r.localTime} · {r.occurrenceCount} appuntamenti · {r.id.slice(0,8)}</option>)}</select></label><p>Vengono annullati solo gli interventi ancora pianificati della serie, liberando le ore. Gli interventi completati o approvati restano invariati.</p><label>Motivazione<textarea name="reason" required maxLength={2000}/></label></>}
      {error&&<p role="alert" className="alert error">{error}</p>}<div className="modal-footer"><button type="button" className="secondary" disabled={busy} onClick={()=>setForm('')}>Indietro</button><button disabled={busy}>{busy?'Salvataggio…':'Conferma'}</button></div>
    </OperationForm></section></div>}
  </section>;
}
function OperationForm({save,children}:{save:(e:React.FormEvent<HTMLFormElement>)=>void;children:React.ReactNode}){const[key]=useState(()=>crypto.randomUUID());return <form data-key={key} onSubmit={save}>{children}</form>}
export function Alerts({state,session,onSaved,navigate}:Props){
  const[error,setError]=useState(''),[busy,setBusy]=useState(false),[resolved,setResolved]=useState(false);
  async function send(action:string,input:any){setBusy(true);setError('');try{const r=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf,'X-Tenant-Context':session.user.tenantId,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(input)});const data=await r.json();if(!r.ok)throw Error(data.error);await onSaved();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  const list=(state.alerts||[]).filter((a:any)=>resolved||!a.resolvedAt);
  return <section><p>Gli avvisi si aggiornano al caricamento dei dati. Le notifiche operative sono interne all’app; non inviano email.</p><details><summary>Configura soglie</summary><form className="ops-filters" onSubmit={e=>{e.preventDefault();void send('alert-settings',Object.fromEntries(new FormData(e.currentTarget)))}}><label>Saldo basso (minuti)<input name="lowBalanceMinutes" type="number" min={0} max={600000} defaultValue={state.company.lowBalanceMinutes} required/></label><label>Ricontatto preventivi (giorni)<input name="quoteFollowupDays" type="number" min={1} max={365} defaultValue={state.company.quoteFollowupDays} required/></label><label>Attesa approvazione (ore)<input name="pendingApprovalHours" type="number" min={1} max={8760} defaultValue={state.company.pendingApprovalHours} required/></label><button disabled={busy}>Salva soglie</button></form></details><label><input type="checkbox" checked={resolved} onChange={e=>setResolved(e.target.checked)}/> Mostra anche risolti</label>{error&&<p role="alert">{error}</p>}{!list.length&&<p>Nessun avviso da mostrare.</p>}<div className="ops-alerts">{list.map((a:any)=><article key={a.id}><h3>{a.title}</h3><p>{a.body}</p><p>{a.resolvedAt?'Risolto':a.readAt?'Letto':'Da leggere'}</p><div className="actions"><button className="secondary" onClick={()=>navigate(a.link)}>Apri {a.link.toLowerCase()}</button>{!a.readAt&&<button disabled={busy} onClick={()=>send('alert-read',{id:a.id})}>Segna come letto</button>}</div></article>)}</div></section>;
}
export function Dashboard({state,session}:Pick<Props,'state'|'session'>){
  const[from,setFrom]=useState(''),[to,setTo]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();setError('');setData(null);fetch('/api/dashboard?'+new URLSearchParams({from,to}),{signal:controller.signal,headers:{'X-Tenant-Context':session.user.tenantId}}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[from,to,state]);
  return <section><h2>Cruscotto operativo</h2><div className="ops-filters"><label>Dal<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Al<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label></div><p className="muted">Importi IVA inclusa. Emesso per data documento, incassato per data pagamento; attività per data appuntamento. Escluse fatture in bozza o annullate. Date Europe/Rome.</p>{error&&<p role="alert">{error}</p>}{data?<div className="stats">{[['Totale emesso',euro(data.issuedTotal)],['Totale incassato',euro(data.paidTotal)],['Ore approvate',hours(data.approvedMinutes)],['Interventi pianificati',String(data.plannedCount)]].map(([label,value])=><article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>:!error&&<p>Caricamento indicatori…</p>}</section>;
}
