import {useEffect,useState} from 'react';
import {post,Session} from './access';
import './platform.css';

type Company={id:string;slug:string;name:string;active:boolean;users:number;clients:number};
const events:Record<string,string>={admin_setup:'Amministratori iniziali creati',company_create:'Impresa creata',company_enter:'Accesso amministrativo all’impresa',company_leave:'Ritorno al pannello',company_suspend:'Impresa sospesa',company_activate:'Impresa riattivata',admin_profile:'Profilo amministratore aggiornato',user_password_reset:'Password aziendale reimpostata',privacy_request_create:'Richiesta privacy registrata',privacy_request_status:'Stato richiesta privacy aggiornato',privacy_export_generate:'Export privacy generato'};
export function Platform({session,onSession,onLogout}:{session:Session;onSession:(s:Session)=>void;onLogout:()=>void}) {
  const [data,setData]=useState<any>({companies:[],administrators:[],audit:[]}),[mail,setMail]=useState<any>({mode:'',from:'',fromName:'',messages:[]}),[monitor,setMonitor]=useState<any>(null),[privacy,setPrivacy]=useState<any[]>([]),[privacySubjects,setPrivacySubjects]=useState<any>({clients:[],users:[]}),[privacyCompany,setPrivacyCompany]=useState(''),[privacyType,setPrivacyType]=useState('client'),[search,setSearch]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<any>(null),[users,setUsers]=useState<any[]>([]),[mfa,setMfa]=useState<any>(null),[mfaSetup,setMfaSetup]=useState<any>(null),[recovery,setRecovery]=useState<string[]>([]);
  async function load(){const [r,m,o,p,f]=await Promise.all([fetch('/api/platform/state'),fetch('/api/platform/mail'),fetch('/api/platform/monitoring'),fetch('/api/platform/privacy'),fetch('/api/mfa/status')]);if(!r.ok)throw Error('Impossibile caricare il pannello amministrativo.');setData(await r.json());if(m.ok)setMail(await m.json());if(o.ok)setMonitor(await o.json());if(p.ok)setPrivacy(await p.json());if(f.ok)setMfa(await f.json());}
  async function loadPrivacySubjects(company:string){setPrivacyCompany(company);setPrivacySubjects({clients:[],users:[]});if(!company)return;const r=await fetch('/api/platform/privacy-subjects?company='+encodeURIComponent(company));if(r.ok)setPrivacySubjects(await r.json());}
  async function downloadPrivacyExport(id:string){setError('');try{const r=await fetch('/api/platform/privacy-export',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf},body:JSON.stringify({id})});if(!r.ok){const j=await r.json();throw Error(j.error);}const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='luviqai-privacy-'+id+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);await load();}catch(e:any){setError(e.message);}}
  useEffect(()=>{document.title='luviqAI · Amministrazione';document.documentElement.style.setProperty('--brand','#176653');load().catch(e=>setError(e.message));},[]);
  async function enter(company:Company){setError('');setBusy(true);try{onSession(await post('platform/switch',{id:company.id},session.csrf));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function startMfa(){setBusy(true);setError('');setNotice('');try{setMfaSetup(await post('mfa/setup',{},session.csrf));setRecovery([]);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function enableMfaForm(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const result=await post('mfa/enable',Object.fromEntries(new FormData(e.currentTarget)),session.csrf);setRecovery(result.recoveryCodes||[]);setMfa({...mfa,enabled:true});setMfaSetup(null);setNotice('Verifica in due passaggi attivata sul profilo amministratore.');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function disableMfaForm(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await post('mfa/disable',Object.fromEntries(new FormData(e.currentTarget)),session.csrf);setMfa({...mfa,enabled:false});setRecovery([]);setNotice('Verifica in due passaggi disattivata sul profilo amministratore.');(e.currentTarget as HTMLFormElement).reset();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function manage(company:Company){setError('');try{const r=await fetch('/api/platform/users?company='+encodeURIComponent(company.id));if(!r.ok)throw Error('Impossibile caricare gli account.');setUsers(await r.json());setModal({kind:'users',company});}catch(e:any){setError(e.message);}}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fields=Object.fromEntries(new FormData(e.currentTarget));try{
    if(modal.kind==='create')await post('platform/create',fields,session.csrf);
    if(modal.kind==='status')await post('platform/status',{...fields,id:modal.company.id,active:!modal.company.active},session.csrf);
    if(modal.kind==='reset')await post('platform/reset-user',{...fields,id:modal.user.id,companyId:modal.company.id},session.csrf);
    if(modal.kind==='profile'){await post('platform/profile',fields,session.csrf);const r=await fetch('/api/me');onSession(await r.json());}
    if(modal.kind==='password'){await post('password',fields,session.csrf);onLogout();return;}
    if(modal.kind==='mail-test')await post('platform/mail',{recipient:fields.recipient,test:true},session.csrf);
    if(modal.kind==='mail-send')await post('platform/mail',{recipient:fields.recipient,subject:fields.subject,message:fields.message},session.csrf);
    if(modal.kind==='privacy-create')await post('platform/privacy',{tenantId:fields.tenantId,subjectType:privacyType,subjectId:fields.subjectId,requesterName:fields.requesterName,requesterEmail:fields.requesterEmail,requestType:fields.requestType,notes:fields.notes},session.csrf);
    if(modal.kind==='privacy-status')await post('platform/privacy-status',{id:modal.request.id,status:fields.status,notes:fields.notes},session.csrf);
    const created=modal.kind==='create';const mailAction=modal.kind==='mail-test'||modal.kind==='mail-send';const privacyAction=modal.kind==='privacy-create'||modal.kind==='privacy-status';setModal(null);setNotice(created?'Impresa creata. Email di accesso del primo responsabile inserita in coda.':mailAction?'Email inserita in coda di invio.':privacyAction?'Richiesta privacy aggiornata.':'Operazione completata e registrata.');await load();
  }catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <div className="platform-shell"><div className="platform-top"><div><span className="brand-icon">✳</span><b>luviqAI</b><span>Amministrazione piattaforma</span></div><div><span>{session.user.name}</span><button className="secondary" onClick={()=>{setError('');setModal({kind:'profile'});}}>Il mio profilo</button><button className="secondary" onClick={()=>{setError('');setModal({kind:'password'});}}>Password</button><button onClick={onLogout}>Esci</button></div></div><div className="platform-content"><header><div><div className="eyebrow">CONTROLLO DELLA PIATTAFORMA</div><h1>Tutte le imprese, un unico pannello.</h1><p>Gestisci le aziende e i loro accessi. Le operazioni riportano sempre il tuo nome nello storico.</p></div><button onClick={()=>{setError('');setModal({kind:'create'});}}>＋ Nuova impresa</button></header>
    {error&&!modal&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}</div>}
    <div className="stats"><div className="metric"><span>Imprese</span><strong>{data.companies.length}</strong></div><div className="metric"><span>Attive</span><strong>{data.companies.filter((c:Company)=>c.active).length}</strong></div><div className="metric"><span>Account aziendali</span><strong>{data.companies.reduce((sum:number,c:Company)=>sum+c.users,0)}</strong></div><div className="metric"><span>Amministratori luviqAI</span><strong>{data.administrators.filter((a:any)=>a.active).length}</strong></div></div>
    <h2>Monitoraggio piattaforma</h2>{monitor?<><div className="stats"><div className="metric"><span>Richieste 24h</span><strong>{monitor.requests?.total||0}</strong><small>{monitor.requests?.lastHour||0} nell’ultima ora</small></div><div className="metric"><span>Errori 24h</span><strong>{monitor.requests?.errors||0}</strong><small>HTTP 5xx registrati</small></div><div className="metric"><span>Tempo medio API</span><strong>{monitor.requests?.avgMs||0} ms</strong><small>Massimo {monitor.requests?.maxMs||0} ms</small></div><div className="metric"><span>Sessioni attive</span><strong>{monitor.sessions?.active||0}</strong><small>Utenti con sessione valida</small></div></div><article className="settings-card"><div className="row"><div><strong>Stato servizi</strong><p>Database: {monitor.database?.kind||'—'} · Email: {monitor.email?.mode||'—'} · Uptime: {Math.floor((monitor.uptimeSeconds||0)/60)} min</p></div><div><span className={'badge '+(monitor.database?.ok?'approved':'cancelled')}>{monitor.database?.ok?'Database OK':'Database KO'}</span> <span className={'badge '+(monitor.email?.ok?'approved':'cancelled')}>{monitor.email?.ok?'Email OK':'Email KO'}</span></div></div><p>Email ultime 24h: <b>{monitor.mail24h?.sent||0}</b> inviate · {monitor.mail24h?.queued||0} in coda · {monitor.mail24h?.uncertain||0} da verificare</p><details><summary>Endpoint più utilizzati</summary>{monitor.endpoints?.length?monitor.endpoints.map((x:any)=><p key={x.path}><code>{x.path}</code> · {x.calls} chiamate · {x.avgMs} ms medi · {x.errors} errori</p>):<p>Nessun dato ancora disponibile.</p>}</details><details><summary>Errori tecnici recenti</summary>{monitor.recentErrors?.length?monitor.recentErrors.map((x:any,i:number)=><p key={i}>{new Date(x.date).toLocaleString('it-IT')} · <b>{x.status}</b> {x.method} <code>{x.path}</code> · {x.durationMs} ms{x.error?' · '+x.error:''}</p>):<p>Nessun errore tecnico nelle ultime 24 ore.</p>}</details><div className="actions"><button className="secondary" onClick={()=>load().catch(e=>setError(e.message))}>Aggiorna monitoraggio</button></div></article></>:<article className="settings-card"><p>Caricamento monitoraggio…</p></article>}
    <h2>Privacy e richieste GDPR</h2><article className="settings-card"><div className="row"><div><strong>Richieste degli interessati</strong><p>Registra, verifica e prepara gli export senza includere password, token di sessione o allegati binari.</p></div><button onClick={()=>{setError('');setPrivacyCompany('');setPrivacyType('client');setPrivacySubjects({clients:[],users:[]});setModal({kind:'privacy-create'});}}>＋ Nuova richiesta</button></div>{privacy.length?<div className="client-grid">{privacy.slice(0,12).map((r:any)=><article className="client-card" key={r.id}><span className={'badge '+(r.status==='closed'||r.status==='delivered'?'approved':r.status==='rejected'?'cancelled':'pending')}>{({received:'Ricevuta',verified:'Identità verificata',preparing:'In preparazione',ready:'Pronta',delivered:'Consegnata',closed:'Chiusa',rejected:'Respinta'} as any)[r.status]||r.status}</span><h3>{r.subject_name}</h3><p>{r.company_name} · {r.subject_type==='client'?'Cliente':'Utente'}</p><p>Tipo: {({access:'Accesso',export:'Portabilità/export',rectification:'Rettifica',erasure:'Cancellazione',restriction:'Limitazione',objection:'Opposizione'} as any)[r.request_type]||r.request_type}</p><small>Ricevuta {new Date(r.created).toLocaleDateString('it-IT')} · Scadenza interna {new Date(r.due_at).toLocaleDateString('it-IT')}</small><div className="actions"><button className="secondary" onClick={()=>setModal({kind:'privacy-status',request:r})}>Aggiorna stato</button>{['verified','preparing','ready','delivered','closed'].includes(r.status)&&<button className="secondary" onClick={()=>void downloadPrivacyExport(r.id)}>Esporta JSON</button>}</div></article>)}</div>:<div className="empty"><p>Nessuna richiesta privacy registrata.</p></div>}</article>
    <h2>Email di sistema</h2><article className="settings-card"><div className="row"><div><strong>{mail.fromName||'luviqAI'} &lt;{mail.from||'non configurato'}&gt;</strong><p>Trasporto: <b>{mail.mode||'—'}</b> · URL pubblico: {mail.publicOrigin||'—'}</p></div><span className={'badge '+(mail.mode==='resend'?'approved':'cancelled')}>{mail.mode==='resend'?'Resend attivo':mail.mode||'Non configurato'}</span></div><div className="actions"><button className="secondary" onClick={()=>{setError('');setModal({kind:'mail-test'});}}>Invia prova</button><button onClick={()=>{setError('');setModal({kind:'mail-send'});}}>Nuova comunicazione</button></div>{mail.messages?.length>0&&<details><summary>Ultimi invii di sistema</summary>{mail.messages.slice(0,5).map((m:any)=><p key={m.id}>{new Date(m.created).toLocaleString('it-IT')} · {m.recipient} · <b>{m.status}</b> · {m.subject}</p>)}</details>}</article>
    <input className="search" aria-label="Cerca impresa" placeholder="Cerca un’impresa…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="package-grid">{data.companies.filter((c:Company)=>(c.name+' '+c.slug).toLowerCase().includes(search.toLowerCase())).map((c:Company)=><article className="package" key={c.id}><div className="row"><h3>{c.name}</h3><span className={'badge '+(c.active?'approved':'cancelled')}>{c.active?'Attiva':'Sospesa'}</span></div><p>Codice: <b>{c.slug}</b> · {c.clients} clienti · {c.users} account</p><div className="actions"><button disabled={busy} onClick={()=>enter(c)}>Apri impresa →</button><button className="secondary" onClick={()=>manage(c)}>Account</button><button className="text" onClick={()=>{setError('');setModal({kind:'status',company:c});}}>{c.active?'Sospendi':'Riattiva'}</button></div></article>)}</div>
    {!data.companies.length&&<div className="empty">Non ci sono ancora imprese. Crea la prima dal pulsante in alto.</div>}
    <h2>Amministratori della piattaforma</h2><div className="admin-members">{data.administrators.map((a:any)=><article className="settings-card" key={a.id}><strong>{a.name}</strong><p>{a.email}</p><span className="badge approved">{a.active?'Amministratore attivo':'Disattivato'}</span></article>)}</div>
    <h2>Registro amministrativo</h2><div className="history">{data.audit.map((a:any)=><article key={a.id}><div className="history-dot"/><div><strong>{events[a.action]||a.action}</strong><p>{new Date(a.date).toLocaleString('it-IT')} · {a.author}</p><details><summary>Dettagli</summary><pre>{JSON.stringify(a.details,null,2)}</pre></details></div></article>)}</div><p className="muted">Ultime 200 operazioni amministrative. Le modifiche a clienti, pacchetti e interventi sono nello storico della rispettiva impresa.</p>
  </div>{modal&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="platform-modal"><div className="row"><h2 id="platform-modal">{({create:'Nuova impresa',status:modal.company?.active?'Sospendi impresa':'Riattiva impresa',profile:'Il mio profilo',password:'Cambia password',users:'Account aziendali',reset:'Reimposta password','mail-test':'Email di prova','mail-send':'Nuova comunicazione','privacy-create':'Nuova richiesta privacy','privacy-status':'Aggiorna richiesta privacy'} as any)[modal.kind]}</h2><button className="text" aria-label="Chiudi" disabled={busy} onClick={()=>setModal(null)}>×</button></div>
  {modal.kind==='users'?<><p>{modal.company.name}</p>{users.map(u=><div className="member" key={u.id}><div><b>{u.name}</b><p>{u.email} · {u.role==='manager'?'Responsabile':'Operatore'} · {u.active?'Attivo':'Disattivato'}</p></div><button className="secondary" onClick={()=>setModal({...modal,kind:'reset',user:u})}>Reimposta password</button></div>)}<p>Per creare o disattivare account, apri l’impresa e usa “Azienda e account”.</p></>:modal.kind==='profile'?<><form onSubmit={submit}><label>Nome<input name="name" required defaultValue={session.user.name}/></label><label>Email di accesso<input name="email" type="email" required defaultValue={session.user.email}/></label>{error&&<div className="alert error" role="alert">{error}</div>}<div className="modal-footer"><button type="button" disabled={busy} className="secondary" onClick={()=>setModal(null)}>Indietro</button><button disabled={busy}>{busy?'Salvataggio…':'Salva profilo'}</button></div></form><hr/><h3>Sicurezza dell’account</h3><p>La verifica in due passaggi protegge il tuo profilo amministratore globale, indipendentemente dall’impresa che apri.</p>{mfa?.available===false?<div className="alert">MFA non disponibile nella configurazione del server.</div>:mfa?.enabled?<><div className="alert success">MFA attiva sul profilo amministratore.</div><form onSubmit={disableMfaForm}><label>Password attuale<input name="password" type="password" autoComplete="current-password" required/></label><label>Codice autenticatore<input name="code" inputMode="numeric" autoComplete="one-time-code" required maxLength={6}/></label><button className="secondary" disabled={busy}>Disattiva MFA</button></form></>:mfaSetup?<><p>Aggiungi questo account nella tua app autenticatore. Puoi aprire il collegamento o inserire manualmente la chiave.</p><p><a className="button secondary" href={mfaSetup.uri}>Apri nell’app autenticatore</a></p><label>Chiave segreta<input readOnly value={mfaSetup.secret}/></label><form onSubmit={enableMfaForm}><label>Codice a 6 cifre<input name="code" inputMode="numeric" autoComplete="one-time-code" required minLength={6} maxLength={6}/></label><button disabled={busy}>Conferma e attiva MFA</button></form></>:<button type="button" disabled={busy||!mfa} onClick={startMfa}>Configura MFA</button>}{recovery.length>0&&<div className="alert"><b>Codici di recupero — mostrati una sola volta</b><pre>{recovery.join('\n')}</pre></div>}</>:<form onSubmit={submit}>
  {modal.kind==='create'&&<><label>Nome impresa<input name="name" required maxLength={300}/></label><label>Codice di accesso<input name="slug" required pattern="[a-z0-9-]{3,50}" placeholder="es. impresa-rossi"/></label><label>Nome responsabile<input name="userName" required/></label><label>Email responsabile<input name="email" type="email" required/></label><label>Password iniziale<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={200}/></label><p>Verranno creati uno spazio aziendale vuoto e il suo primo responsabile. Il riepilogo di accesso verrà inviato via email senza password; comunica la password iniziale separatamente.</p></>}
  {modal.kind==='status'&&<><p>{modal.company.name}: {modal.company.active?'gli accessi aziendali verranno sospesi e le sessioni chiuse. Dati e storico rimangono disponibili agli amministratori.':'gli account attivi potranno nuovamente accedere.'}</p><label>Motivazione<textarea name="reason" required maxLength={2000}/></label></>}
  {modal.kind==='password'&&<><label>Password attuale<input name="currentPassword" type="password" required autoComplete="current-password"/></label><label>Nuova password<input name="password" type="password" required minLength={12} maxLength={200} autoComplete="new-password"/></label><p>La modifica chiuderà tutte le tue sessioni.</p></>}
  {modal.kind==='reset'&&<><p>{modal.user.name} · {modal.user.email}</p><label>Nuova password iniziale<input name="password" type="password" required minLength={12} maxLength={200} autoComplete="new-password"/></label><label>Motivazione<textarea name="reason" required maxLength={2000}/></label><p>Le sessioni e i precedenti link di recupero di questo account verranno invalidati. La password non compare nello storico.</p></>}
  {modal.kind==='mail-test'&&<><p>Invia un messaggio di prova usando il mittente globale <b>{mail.fromName} &lt;{mail.from}&gt;</b>.</p><label>Destinatario<input name="recipient" type="email" required defaultValue={session.user.email}/></label></>}
  {modal.kind==='mail-send'&&<><p>Invia una comunicazione amministrativa dal mittente globale <b>{mail.fromName} &lt;{mail.from}&gt;</b>.</p><label>Destinatario<input name="recipient" type="email" required/></label><label>Oggetto<input name="subject" required maxLength={200}/></label><label>Messaggio<textarea name="message" required maxLength={5000} rows={8}/></label></>}
  {modal.kind==='privacy-create'&&<><label>Azienda<select name="tenantId" required value={privacyCompany} onChange={e=>void loadPrivacySubjects(e.target.value)}><option value="">Seleziona azienda</option>{data.companies.map((c:Company)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tipo interessato<select value={privacyType} onChange={e=>setPrivacyType(e.target.value)}><option value="client">Cliente</option><option value="user">Utente aziendale</option></select></label><label>Interessato<select name="subjectId" required disabled={!privacyCompany}><option value="">Seleziona interessato</option>{(privacyType==='client'?privacySubjects.clients:privacySubjects.users).map((x:any)=><option key={x.id} value={x.id}>{x.name}{x.email?' · '+x.email:''}</option>)}</select></label><label>Nome richiedente<input name="requesterName" required maxLength={200}/></label><label>Email richiedente<input name="requesterEmail" type="email"/></label><label>Tipo richiesta<select name="requestType" defaultValue="access"><option value="access">Accesso ai dati</option><option value="export">Portabilità / export</option><option value="rectification">Rettifica</option><option value="erasure">Cancellazione</option><option value="restriction">Limitazione</option><option value="objection">Opposizione</option></select></label><label>Note<textarea name="notes" maxLength={3000}/></label><p>L’export sarà disponibile solo dopo aver segnato l’identità come verificata. Prima della consegna va revisionato per evitare dati riferiti a terzi.</p></>}
  {modal.kind==='privacy-status'&&<><p><b>{modal.request.subject_name}</b> · {modal.request.company_name}</p><label>Stato<select name="status" defaultValue={modal.request.status}><option value="received">Ricevuta</option><option value="verified">Identità verificata</option><option value="preparing">In preparazione</option><option value="ready">Pronta</option><option value="delivered">Consegnata</option><option value="closed">Chiusa</option><option value="rejected">Respinta</option></select></label><label>Note<textarea name="notes" maxLength={3000} defaultValue={modal.request.notes||''}/></label></>}
  {error&&<div className="alert error" role="alert">{error}</div>}<div className="modal-footer"><button type="button" disabled={busy} className="secondary" onClick={()=>setModal(null)}>Indietro</button><button disabled={busy}>{busy?'Salvataggio…':'Conferma operazione'}</button></div></form>}</section></div>}</div>;
}
