import {useEffect,useState} from 'react';
import {post,Session} from './access';
import './platform.css';

type Company={id:string;slug:string;name:string;active:boolean;users:number;clients:number};
const events:Record<string,string>={admin_setup:'Amministratori iniziali creati',company_create:'Impresa creata',company_enter:'Accesso amministrativo all’impresa',company_leave:'Ritorno al pannello',company_suspend:'Impresa sospesa',company_activate:'Impresa riattivata',admin_profile:'Profilo amministratore aggiornato',user_password_reset:'Password aziendale reimpostata'};
export function Platform({session,onSession,onLogout}:{session:Session;onSession:(s:Session)=>void;onLogout:()=>void}) {
  const [data,setData]=useState<any>({companies:[],administrators:[],audit:[]}),[search,setSearch]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<any>(null),[users,setUsers]=useState<any[]>([]);
  async function load(){const r=await fetch('/api/platform/state');if(!r.ok)throw Error('Impossibile caricare il pannello amministrativo.');setData(await r.json());}
  useEffect(()=>{document.title='luviqAI · Amministrazione';document.documentElement.style.setProperty('--brand','#176653');load().catch(e=>setError(e.message));},[]);
  async function enter(company:Company){setError('');setBusy(true);try{onSession(await post('platform/switch',{id:company.id},session.csrf));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function manage(company:Company){setError('');try{const r=await fetch('/api/platform/users?company='+encodeURIComponent(company.id));if(!r.ok)throw Error('Impossibile caricare gli account.');setUsers(await r.json());setModal({kind:'users',company});}catch(e:any){setError(e.message);}}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fields=Object.fromEntries(new FormData(e.currentTarget));try{
    if(modal.kind==='create')await post('platform/create',fields,session.csrf);
    if(modal.kind==='status')await post('platform/status',{...fields,id:modal.company.id,active:!modal.company.active},session.csrf);
    if(modal.kind==='reset')await post('platform/reset-user',{...fields,id:modal.user.id,companyId:modal.company.id},session.csrf);
    if(modal.kind==='profile'){await post('platform/profile',fields,session.csrf);const r=await fetch('/api/me');onSession(await r.json());}
    if(modal.kind==='password'){await post('password',fields,session.csrf);onLogout();return;}
    const created=modal.kind==='create';setModal(null);setNotice(created?'Impresa creata. Email di accesso del primo responsabile inserita in coda.':'Operazione completata e registrata.');await load();
  }catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <div className="platform-shell"><div className="platform-top"><div><span className="brand-icon">✳</span><b>luviqAI</b><span>Amministrazione piattaforma</span></div><div><span>{session.user.name}</span><button className="secondary" onClick={()=>{setError('');setModal({kind:'profile'});}}>Il mio profilo</button><button className="secondary" onClick={()=>{setError('');setModal({kind:'password'});}}>Password</button><button onClick={onLogout}>Esci</button></div></div><div className="platform-content"><header><div><div className="eyebrow">CONTROLLO DELLA PIATTAFORMA</div><h1>Tutte le imprese, un unico pannello.</h1><p>Gestisci le aziende e i loro accessi. Le operazioni riportano sempre il tuo nome nello storico.</p></div><button onClick={()=>{setError('');setModal({kind:'create'});}}>＋ Nuova impresa</button></header>
    {error&&!modal&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}</div>}
    <div className="stats"><div className="metric"><span>Imprese</span><strong>{data.companies.length}</strong></div><div className="metric"><span>Attive</span><strong>{data.companies.filter((c:Company)=>c.active).length}</strong></div><div className="metric"><span>Account aziendali</span><strong>{data.companies.reduce((sum:number,c:Company)=>sum+c.users,0)}</strong></div><div className="metric"><span>Amministratori luviqAI</span><strong>{data.administrators.filter((a:any)=>a.active).length}</strong></div></div>
    <input className="search" aria-label="Cerca impresa" placeholder="Cerca un’impresa…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="package-grid">{data.companies.filter((c:Company)=>(c.name+' '+c.slug).toLowerCase().includes(search.toLowerCase())).map((c:Company)=><article className="package" key={c.id}><div className="row"><h3>{c.name}</h3><span className={'badge '+(c.active?'approved':'cancelled')}>{c.active?'Attiva':'Sospesa'}</span></div><p>Codice: <b>{c.slug}</b> · {c.clients} clienti · {c.users} account</p><div className="actions"><button disabled={busy} onClick={()=>enter(c)}>Apri impresa →</button><button className="secondary" onClick={()=>manage(c)}>Account</button><button className="text" onClick={()=>{setError('');setModal({kind:'status',company:c});}}>{c.active?'Sospendi':'Riattiva'}</button></div></article>)}</div>
    {!data.companies.length&&<div className="empty">Non ci sono ancora imprese. Crea la prima dal pulsante in alto.</div>}
    <h2>Amministratori della piattaforma</h2><div className="admin-members">{data.administrators.map((a:any)=><article className="settings-card" key={a.id}><strong>{a.name}</strong><p>{a.email}</p><span className="badge approved">{a.active?'Amministratore attivo':'Disattivato'}</span></article>)}</div>
    <h2>Registro amministrativo</h2><div className="history">{data.audit.map((a:any)=><article key={a.id}><div className="history-dot"/><div><strong>{events[a.action]||a.action}</strong><p>{new Date(a.date).toLocaleString('it-IT')} · {a.author}</p><details><summary>Dettagli</summary><pre>{JSON.stringify(a.details,null,2)}</pre></details></div></article>)}</div><p className="muted">Ultime 200 operazioni amministrative. Le modifiche a clienti, pacchetti e interventi sono nello storico della rispettiva impresa.</p>
  </div>{modal&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="platform-modal"><div className="row"><h2 id="platform-modal">{({create:'Nuova impresa',status:modal.company?.active?'Sospendi impresa':'Riattiva impresa',profile:'Il mio profilo',password:'Cambia password',users:'Account aziendali',reset:'Reimposta password'} as any)[modal.kind]}</h2><button className="text" aria-label="Chiudi" disabled={busy} onClick={()=>setModal(null)}>×</button></div>
  {modal.kind==='users'?<><p>{modal.company.name}</p>{users.map(u=><div className="member" key={u.id}><div><b>{u.name}</b><p>{u.email} · {u.role==='manager'?'Responsabile':'Operatore'} · {u.active?'Attivo':'Disattivato'}</p></div><button className="secondary" onClick={()=>setModal({...modal,kind:'reset',user:u})}>Reimposta password</button></div>)}<p>Per creare o disattivare account, apri l’impresa e usa “Azienda e account”.</p></>:<form onSubmit={submit}>
  {modal.kind==='create'&&<><label>Nome impresa<input name="name" required maxLength={300}/></label><label>Codice di accesso<input name="slug" required pattern="[a-z0-9-]{3,50}" placeholder="es. impresa-rossi"/></label><label>Nome responsabile<input name="userName" required/></label><label>Email responsabile<input name="email" type="email" required/></label><label>Password iniziale<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={200}/></label><p>Verranno creati uno spazio aziendale vuoto e il suo primo responsabile. Il riepilogo di accesso verrà inviato via email senza password; comunica la password iniziale separatamente.</p></>}
  {modal.kind==='status'&&<><p>{modal.company.name}: {modal.company.active?'gli accessi aziendali verranno sospesi e le sessioni chiuse. Dati e storico rimangono disponibili agli amministratori.':'gli account attivi potranno nuovamente accedere.'}</p><label>Motivazione<textarea name="reason" required maxLength={2000}/></label></>}
  {modal.kind==='profile'&&<><label>Nome<input name="name" required defaultValue={session.user.name}/></label><label>Email di accesso<input name="email" type="email" required defaultValue={session.user.email}/></label></>}
  {modal.kind==='password'&&<><label>Password attuale<input name="currentPassword" type="password" required autoComplete="current-password"/></label><label>Nuova password<input name="password" type="password" required minLength={12} maxLength={200} autoComplete="new-password"/></label><p>La modifica chiuderà tutte le tue sessioni.</p></>}
  {modal.kind==='reset'&&<><p>{modal.user.name} · {modal.user.email}</p><label>Nuova password iniziale<input name="password" type="password" required minLength={12} maxLength={200} autoComplete="new-password"/></label><label>Motivazione<textarea name="reason" required maxLength={2000}/></label><p>Le sessioni e i precedenti link di recupero di questo account verranno invalidati. La password non compare nello storico.</p></>}
  {error&&<div className="alert error" role="alert">{error}</div>}<div className="modal-footer"><button type="button" disabled={busy} className="secondary" onClick={()=>setModal(null)}>Indietro</button><button disabled={busy}>{busy?'Salvataggio…':'Conferma operazione'}</button></div></form>}</section></div>}</div>;
}
