import React,{useEffect,useState} from 'react';
import {Session} from './access';
export type Quote={emailStatus?:string|null;emailMode?:string|null;id:number;clientId:number;number:string;revision:number;status:string;issueDate:string;validUntil:string;document:any;net:number;tax:number;total:number;sourceId:number|null};
const statuses:Record<string,string>={draft:'Bozza',sent:'Inviato',accepted:'Accettato',rejected:'Rifiutato',cancelled:'Annullato'};
const money=(v:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(v/100);
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Rome'}).format(new Date());
const date=(s:string)=>s.split('-').reverse().join('/');
type Line={description:string;quantity:string;unitPrice:string;vat:string;discount:string};
const blank=():Line=>({description:'',quantity:'1',unitPrice:'0',vat:'0',discount:'0'});
function scaled(s:string){const v=s.replace(',','.');if(!/^\d+(\.\d{1,2})?$/.test(v))throw Error('Quantità, prezzi e percentuali devono essere numeri positivi con al massimo due decimali.');const [a,b='']=v.split('.');return Number(a)*100+Number(b.padEnd(2,'0'));}
export function Quotes({items,clients,catalog,session,onSaved,clientFilter}:{items:Quote[];clients:any[];catalog:any[];session:Session;onSaved:()=>Promise<void>;clientFilter?:number}){
  const [selected,setSelected]=useState<number|null>(null),[editor,setEditor]=useState<any>(null),[confirmation,setConfirmation]=useState<any>(null),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pdfBusy,setPdfBusy]=useState(false),[pdfNotice,setPdfNotice]=useState('');
  const q=items.find(x=>x.id===selected);
  useEffect(()=>{document.body.classList.toggle('quote-print',!!q&&!editor);return()=>document.body.classList.remove('quote-print');},[q,editor]);
  function edit(item?:Quote,copy=false){setError('');setEditor({key:crypto.randomUUID(),item:copy?null:item,sourceId:copy?item?.id:null,clientId:item?.clientId||clientFilter||'',title:item?.document.title||'',issueDate:copy||!item?today():item.issueDate,validUntil:copy||!item?new Date(Date.now()+30*86400000).toISOString().slice(0,10):item.validUntil,notes:item?.document.notes||'',terms:item?.document.terms||'',lines:item?item.document.lines.map((l:any)=>({description:l.description,quantity:String(l.quantity/100),unitPrice:(l.unitPrice/100).toFixed(2),vat:String(l.vat/100),discount:String(l.discount/100)})):[blank()]});}
  async function send(action:string,input:any,key:string){setBusy(true);setError('');try{const r=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key,'X-CSRF-Token':session.csrf,'X-Tenant-Context':session.user.tenantId},body:JSON.stringify(input)});const result=await r.json();if(!r.ok){if(r.status===409)await onSaved();if(editor)setEditor({...editor,key:crypto.randomUUID()});if(confirmation)setConfirmation({...confirmation,key:crypto.randomUUID()});throw Error(result.error)}await onSaved();setSelected(result.value?.id||selected);setEditor(null);setConfirmation(null);if(action==='quote-email')setPdfNotice(result.mode==='preview'?'Email simulata preparata. Apri Email e notifiche per leggere il messaggio e provare la pagina cliente.':'Email in coda. Segui l’esito in Email e notifiche.');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function downloadPDF(){if(!q||pdfBusy)return;setPdfBusy(true);setError('');setPdfNotice('');try{const r=await fetch('/api/quotes/'+q.id+'/pdf',{headers:{'X-Tenant-Context':session.user.tenantId}});if(!r.ok){const result=await r.json();throw Error(result.error||'Impossibile generare il PDF.')}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=q.number+'.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);setPdfNotice('PDF generato. Apri il file scaricato e scegli Stampa nel lettore PDF.');}catch(e:any){setError(e.message)}finally{setPdfBusy(false)}}
  function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();try{const reason=new FormData(e.currentTarget).get('reason');const lines=editor.lines.map((l:Line)=>({...l,quantity:scaled(l.quantity),unitPrice:scaled(l.unitPrice),vat:scaled(l.vat),discount:scaled(l.discount)}));void send('quote',{id:editor.item?.id,revision:editor.item?.revision,sourceId:editor.sourceId,clientId:editor.clientId,title:editor.title,issueDate:editor.issueDate,validUntil:editor.validUntil,notes:editor.notes,terms:editor.terms,lines,reason},editor.key);}catch(e:any){setError(e.message)}}
  function change(field:string,value:any){setEditor({...editor,[field]:value});}
  function lineChange(index:number,field:keyof Line,value:string){change('lines',editor.lines.map((l:Line,i:number)=>i===index?{...l,[field]:value}:l));}
  const visible=items.filter(x=>(!clientFilter||x.clientId===clientFilter)&&(filter==='all'||x.status===filter)&&(x.number+' '+x.document.title+' '+x.document.client.name).toLowerCase().includes(search.toLowerCase()));
  return <section className="quotes-page">
    {error&&<div className="alert error" role="alert">{error}</div>}
    {editor?<form className="quote-editor" onSubmit={save}><fieldset disabled={busy}><div className="section-title"><h2>{editor.item?'Modifica bozza':'Nuovo preventivo'}</h2><button type="button" className="secondary" onClick={()=>{setEditor(null);setError('')}}>Indietro</button></div>
      <div className="form-grid"><label>Cliente del preventivo *<select required value={editor.clientId} onChange={e=>change('clientId',Number(e.target.value))}><option value="">Seleziona cliente</option>{clients.filter(c=>!c.archived).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Oggetto *<input required maxLength={200} value={editor.title} onChange={e=>change('title',e.target.value)}/></label><label>Data del preventivo *<input type="date" required value={editor.issueDate} onChange={e=>change('issueDate',e.target.value)}/></label><label>Valido fino al *<input type="date" required min={editor.issueDate} value={editor.validUntil} onChange={e=>change('validUntil',e.target.value)}/></label></div>
      <h3>Voci del preventivo</h3><p className="help">Prezzi unitari al netto dell’IVA. Inserisci l’aliquota applicabile per ogni voce. I totali sono calcolati e verificati al salvataggio.</p>
      {editor.lines.map((l:Line,i:number)=><div className="quote-line" key={i}><label>Descrizione voce {i+1} *<textarea required maxLength={500} value={l.description} onChange={e=>lineChange(i,'description',e.target.value)}/></label><div className="quote-numbers">{(['quantity','unitPrice','discount','vat'] as const).map((field,j)=><label key={field}>{['Quantità','Prezzo unitario €','Sconto %','IVA %'][j]}<input aria-label={['Quantità','Prezzo unitario','Sconto','IVA'][j]+' voce '+(i+1)} type="number" step="0.01" min={field==='quantity'?'0.01':'0'} max={field==='quantity'?10000:field==='unitPrice'?100000:100} required value={l[field]} onChange={e=>lineChange(i,field,e.target.value)}/></label>)}</div><button type="button" className="text danger" disabled={editor.lines.length===1} onClick={()=>change('lines',editor.lines.filter((_:any,n:number)=>n!==i))}>Rimuovi voce {i+1}</button></div>)}
      <div className="actions"><button type="button" className="secondary" disabled={editor.lines.length>=30} onClick={()=>change('lines',[...editor.lines,blank()])}>＋ Aggiungi voce</button><label>Inserisci dal catalogo<select value="" disabled={editor.lines.length>=30} onChange={e=>{const t=catalog.find(c=>c.id===Number(e.target.value));if(t)change('lines',[...editor.lines,{...blank(),description:`${t.name} · ${Math.floor(t.minutes/60)} h ${t.minutes%60} min · per ${t.rule==='operator'?'operatore':'squadra'}${t.description?'\n'+t.description:''}`.slice(0,500)}])}}><option value="">Scegli un modello</option>{catalog.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
      <label>Condizioni e modalità di pagamento<textarea maxLength={2000} value={editor.terms} onChange={e=>change('terms',e.target.value)}/></label><label>Note per il cliente<textarea maxLength={2000} value={editor.notes} onChange={e=>change('notes',e.target.value)}/></label>{editor.item&&<label>Motivazione della modifica *<textarea name="reason" required maxLength={2000}/></label>}
      <div className="alert">Il salvataggio crea una bozza. Potrai verificare i totali e stampare il documento prima di registrare l’invio.</div><button type="submit">{busy?'Salvataggio…':'Salva bozza'}</button>
    </fieldset></form>:q?<>
      <div className="actions quote-actions">{['draft','sent'].includes(q.status)&&!q.emailStatus&&<button onClick={()=>{setError('');setConfirmation({item:q,status:'email',key:crypto.randomUUID()})}}>Invia via email</button>}{q.emailStatus&&<span className="badge">Email: {({queued:'in coda',sending:'in corso',preview:'simulazione pronta',sent:'inviata',uncertain:'da verificare'} as any)[q.emailStatus]||q.emailStatus}</span>}<button className="secondary" onClick={()=>{setSelected(null);setError('')}}>← Elenco preventivi</button>{q.status==='draft'&&<button onClick={()=>edit(q)}>Modifica bozza</button>}<button className="secondary" onClick={()=>edit(q,true)}>Duplica preventivo</button><button className="secondary" disabled={pdfBusy} onClick={downloadPDF}>{pdfBusy?'Preparazione PDF…':'Scarica PDF / Stampa'}</button>{(q.status==='draft'?['sent','cancelled']:q.status==='sent'?['accepted','rejected','cancelled']:q.status==='accepted'?['cancelled']:[]).map(status=><button key={status} className={status==='cancelled'?'text danger':'secondary'} onClick={()=>{setError('');setConfirmation({item:q,status,key:crypto.randomUUID()})}}>{{sent:'Registra invio',accepted:'Registra accettazione',rejected:'Registra rifiuto',cancelled:'Annulla preventivo'}[status]}</button>)}</div>
      {pdfNotice&&<div className="alert success" role="status">{pdfNotice}</div>}<article className="quote-document"><div className="quote-heading"><div><div className="eyebrow">PREVENTIVO</div><h2>{q.number}</h2><span className={'badge '+(q.status==='accepted'?'approved':q.status==='cancelled'||q.status==='rejected'?'cancelled':'pending')}>{statuses[q.status]}</span>{q.status==='sent'&&q.validUntil<today()&&<span className="badge low">Scaduto</span>}</div><div>{q.document.company.logoData&&<img className="quote-company-logo" src={q.document.company.logoData} alt="Logo aziendale"/>}<h3>{q.document.company.name}</h3><p>{q.document.company.address}</p><p>{q.document.company.email} {q.document.company.phone}</p><p>{q.document.company.website}</p>{q.document.company.taxId&&<p>P. IVA / C.F. {q.document.company.taxId}</p>}</div></div>
      <div className="quote-heading"><div><small>DESTINATARIO</small><h3>{q.document.client.name}</h3><p>{q.document.client.address}</p><p>{q.document.client.email} {q.document.client.phone}</p></div><div><p>Data: {date(q.issueDate)}</p><p>Validità: {date(q.validUntil)}</p><p>Versione {q.revision}{q.sourceId?` · da preventivo #${q.sourceId}`:''}</p></div></div><h2>{q.document.title}</h2>
      <div className="table-wrap"><table><thead><tr><th>Descrizione</th><th>Qtà</th><th>Prezzo</th><th>Sconto</th><th>IVA</th><th>Imponibile</th></tr></thead><tbody>{q.document.lines.map((l:any,i:number)=><tr key={i}><td>{l.description}</td><td>{(l.quantity/100).toLocaleString('it-IT')}</td><td>{money(l.unitPrice)}</td><td>{l.discount/100}%</td><td>{l.vat/100}%</td><td>{money(l.net)}</td></tr>)}</tbody></table></div>
      <div className="quote-totals"><p>Imponibile <strong>{money(q.net)}</strong></p><p>IVA <strong>{money(q.tax)}</strong></p><p className="quote-total">Totale <strong>{money(q.total)}</strong></p></div>{q.document.terms&&<><h3>Condizioni</h3><p>{q.document.terms}</p></>}{q.document.notes&&<><h3>Note</h3><p>{q.document.notes}</p></>}<footer>Preventivo commerciale · Realizzato con luviqAI</footer>
      </article>
    </>:<><div className="section-title"><h2>{clientFilter?'Preventivi del cliente':'Proposte commerciali'}</h2><button onClick={()=>edit()}>＋ Nuovo preventivo</button></div><div className="filters">{['all',...Object.keys(statuses)].map(s=><button key={s} className={filter===s?'selected':'secondary'} onClick={()=>setFilter(s)}>{s==='all'?'Tutti':statuses[s]}</button>)}</div><input aria-label="Cerca preventivo" className="search" placeholder="Cerca per numero, cliente o oggetto…" value={search} onChange={e=>setSearch(e.target.value)}/>{visible.length?<div className="client-grid">{visible.map(x=><article className="client-card" key={x.id}><div className="row"><strong>{x.number}</strong><span className="badge">{statuses[x.status]}</span></div><h3>{x.document.title}</h3><p>{x.document.client.name}</p><p>Valido fino al {date(x.validUntil)}{x.status==='sent'&&x.validUntil<today()?' · Scaduto':''}</p><div className="row"><strong>{money(x.total)}</strong><button className="secondary" onClick={()=>setSelected(x.id)}>Apri preventivo</button></div></article>)}</div>:<div className="empty"><span>◇</span><h3>Nessun preventivo da mostrare</h3><p>Crea una proposta per un cliente oppure modifica i filtri di ricerca.</p></div>}</>}
    {confirmation&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="quote-confirm"><h2 id="quote-confirm">Conferma: {confirmation.status==='email'?'invio email':statuses[confirmation.status]}</h2><p>{confirmation.item.number} · {money(confirmation.item.total)}</p><p>{confirmation.status==='email'?`Prepara l’email per ${confirmation.item.document.client.email||'email cliente mancante'}, con il PDF e il collegamento personale per rispondere. In modalità locale il messaggio resta nella simulazione e non viene spedito.`:confirmation.status==='sent'?'Confermi di aver consegnato o inviato il preventivo al cliente? Nessun messaggio verrà spedito dall’app. Il contenuto non sarà più modificabile.':confirmation.status==='accepted'?'Registra l’accettazione ricevuta dal cliente. Questa operazione non crea pacchetti, addebiti o fatture.':'La variazione resterà nello storico. Il documento sarà conservato.'}</p><form onSubmit={e=>{e.preventDefault();void send(confirmation.status==='email'?'quote-email':'quote-status',{id:confirmation.item.id,revision:confirmation.item.revision,status:confirmation.status,reason:new FormData(e.currentTarget).get('reason')},confirmation.key)}}><label>Motivazione o riferimento *<textarea name="reason" required maxLength={2000} disabled={busy}/></label>{error&&<div className="alert error" role="alert">{error}</div>}<div className="actions"><button type="button" className="secondary" disabled={busy} onClick={()=>{setConfirmation(null);setError('')}}>Indietro</button><button disabled={busy} type="submit">{confirmation.status==='email'?'Conferma invio email':'Conferma stato'}</button></div></form></section></div>}
  </section>;
}
